### ISSUE TITLE
make docker报错

### ISSUE THREAD

**Issue by sbwdlihao** [cryptape/cita#1]
```shell
xxx:cita xxx$ make docker
mkdir -p /tmp/cita/build
cp Dockerfile-build /tmp/cita/build/Dockerfile
docker build -t cita/build /tmp/cita/build
......
docker run -ti -v xxx/Git/cita:/sources -u cita cita/build bash -c  "make setup; make release"
mkdir -p admintool/release/
cp .env admintool/release/
sudo rabbitmqctl add_vhost dev                                  >/dev/null 2>&1 || echo "ok"
ok
sudo rabbitmqctl set_permissions -p dev guest ".*" ".*" ".*"    >/dev/null 2>&1
Makefile:25: recipe for target 'setup' failed
make: *** [setup] Error 1
RUSTFLAGS='-F warnings' cargo build --release --all
    Updating registry `https://github.com/rust-lang/crates.io-index`
```
make docker运行到这里就不往下继续运行了。

运行环境
* Darwin MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by rink1969** [comment]
docker模式我们没有充分的测试过。
Mac环境下也可能会遇到一些未知的问题。
建议Mac用户装一个ubuntu 16.04的虚拟机，然后以本地模式编译运行。

**Comment by rink1969** [comment]
这里报错的直接原因是rabbitmq server没起来
不在docker里面的时候，这个服务是随着系统开机自动启动的
docker里面可能要自己 sudo rabbitmq-server start 启动一下

**Comment by urugang** [comment]
这里挂住有一个原因是cargo 的数据不能从github上拉下来， 跟网络有关系, 可以用两种方法解决：  
1） 更换cargo镜像（后续会写到dockerfile里， 用户不需要再配置）
可以配置 ~/.cargo/config   
`
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = "ustc" 

[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

`

2） 给cargo配代理
