### ISSUE TITLE
哪个分支是可以成功编译的?

### ISSUE THREAD

**Issue by dujiacheng** [cryptape/cita#113]
ubuntu@ubuntu:~/cita$ git checkout stable_holiday
Already on 'stable_holiday'
Your branch is up-to-date with 'origin/stable_holiday'.
ubuntu@ubuntu:~/cita$ 
ubuntu@ubuntu:~/cita$ make setup
make: *** No rule to make target 'setup'.  Stop.

**Comment by dujiacheng** [comment]
ubuntu@ubuntu:~/cita$ rustc --version
rustc 1.21.0-nightly (1d2a6df38 2017-08-03)

**Comment by dujiacheng** [comment]
ubuntu@ubuntu:~/cita$ git checkout master 
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
ubuntu@ubuntu:~/cita$ 
ubuntu@ubuntu:~/cita$ make setup
mkdir -p admintool/release/
cp .env admintool/release/
sudo rabbitmqctl add_vhost dev                                  >/dev/null 2>&1 || echo "ok"
[sudo] password for ubuntu: 
[sudo] password for ubuntu: 
ok
sudo rabbitmqctl set_permissions -p dev guest ".*" ".*" ".*"    >/dev/null 2>&1
Makefile:25: recipe for target 'setup' failed
make: *** [setup] Error 1

**Comment by shengling123** [comment]
目前没有make setup，编译make setup1是安装依赖，再make

**Comment by dujiacheng** [comment]
ubuntu@ubuntu:~/cita$ git checkout stable_holiday
Already on 'stable_holiday'
Your branch is up-to-date with 'origin/stable_holiday'.
ubuntu@ubuntu:~/cita$ make setup1
apt-get update -q
W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
Makefile:28: recipe for target 'setup1' failed
make: *** [setup1] Error 100

**Comment by vinberm** [comment]
sudo make setup1 && make setup2

**Comment by dujiacheng** [comment]
ubuntu@ubuntu:~/cita$ sudo make setup1 && make setup2
apt-get update -q
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 306 kB in 2s (108 kB/s)
Reading package lists...
apt-get install --allow-change-held-packages software-properties-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.20.7).
0 upgraded, 0 newly installed, 0 to remove and 140 not upgraded.
if [ $(lsb_release -s -c) = "trusty" ]; then add-apt-repository ppa:chris-lea/libsodium -y ; fi;
apt-get update -q
Hit:1 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 306 kB in 4s (73.3 kB/s)
Reading package lists...
apt-get build-dep build-essential
Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
Makefile:28: recipe for target 'setup1' failed
make: *** [setup1] Error 100

**Comment by vinberm** [comment]
先sudo make setup1，setup2可选的，如果安装了rust，可以不用make setup2。 后面再make debug 或者 make release。

**Comment by dujiacheng** [comment]
我现在是 stable_holiday 这个分支,  rustup rustc 都已经装好了,  sudo make setup1 的时候报错了.

**Comment by vinberm** [comment]
像是你ubuntu中的apt问题，可看下这里 [https://askubuntu.com/questions/496549/error-you-must-put-some-source-uris-in-your-sources-list]

**Comment by vinberm** [comment]
像是ubuntu中apt的问题，可以参考下 [https://askubuntu.com/questions/496549/error-you-must-put-some-source-uris-in-your-sources-list](url)

**Comment by vinberm** [comment]
像是ubuntu中apt的问题，可以参考下 [https://askubuntu.com/questions/496549/error-you-must-put-some-source-uris-in-your-sources-list](https://askubuntu.com/questions/496549/error-you-must-put-some-source-uris-in-your-sources-list)

**Comment by dujiacheng** [comment]
我填加了一些源 到　/etc/apt/sources.list 就好了.
deb-src http://archive.ubuntu.com/ubuntu trusty main restricted #Added by software-properties
deb-src http://gb.archive.ubuntu.com/ubuntu/ trusty restricted main universe multiverse #Added by software-properties
deb-src http://gb.archive.ubuntu.com/ubuntu/ trusty-updates restricted main universe multiverse #Added by software-properties
deb-src http://gb.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse #Added by software-properties
deb-src http://security.ubuntu.com/ubuntu trusty-security restricted main universe multiverse #Added by software-properties
deb-src http://gb.archive.ubuntu.com/ubuntu/ trusty-proposed restricted main universe multiverse #Added by software-properties
