### ISSUE TITLE
Speed up installation process (scripts/install_develop.sh)

### ISSUE THREAD

**Issue by TheWaWaR** [cryptape/cita#146]
## My Environment
* Host System: 
  - MacBook Pro (Retina, 13-inch, Mid 2014) 
  - Processor: 2.6 GHz Intel Core i5
  - Memory: 8 GB 1600 MHz DDR3

* VM System:
  - Ubuntu 16.04.3
  - Processor: 2 CPU
  - Memory: 3 GB

## The Problem
On my machine `scripts/install_develop.sh` takes more than 13 minutes to finish. In some conditions(poor network, poor machine), it may takes more than 30 minutes, which will trigger sudo timeout then fail the installation process. Because download and build solidity is time consuming.

#### Install solidity from PPA (downside: latest stable version only)

``` bash
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install -y solc
```

#### Install solidity by download static linked binary file

``` bash
wget https://github.com/ethereum/solidity/releases/download/v0.4.19/solc-static-linux
chmod +x solc-static-linux
sudo mv solc-static-linux /usr/local/bin/solc
```

Either way, I can make a PR.

**Comment by u2** [comment]
Thank you very much.Yeah, we have considered to replace to the static binary file. Welcome for your PR.
