### ISSUE TITLE
some question in cita V0.13

### ISSUE THREAD

**Issue by agileHua** [cryptape/cita#151]
When you release cita V0.13, it seems that you havent release cita-tendenmit and cita-forever in your source code. How can I get stable version of these two submodule?

**Comment by janx** [comment]
Check these repos in cryptape org:

* https://github.com/cryptape/cita-tendermint
* https://github.com/cryptape/cita-forever

We'll add version tag for components in next release, right now you can use develop branch.

**Comment by janx** [comment]
You should be able to use `git submodule` command to get component code directly. `git submodule` will fetch the appropriate version for you.
