### ISSUE TITLE
Rabbitmq connection refused need better error message

### ISSUE THREAD

**Issue by willsays** [cryptape/cita#153]
2018-02-15T23:50:57.335987479-06:00 - INFO - CITA:jsonrpc
2018-02-15T23:50:57.336084466-06:00 - INFO - Value for config: jsonrpc.toml
2018-02-15T23:50:57.336224077-06:00 - INFO - CITA:jsonrpc config
 "backlog_capacity = 1000\n\n[profile_config]\nenable = false\nflag_prof_start = 0\nflag_prof_duration = 0\n\n[http_config]\nenable = true\nlisten_ip = \'0.0.0.0\'\nlisten_port = \'1337\'\ntimeout = 3\nallow_origin = \'*\'\n\n[ws_config]\nenable = true\nthread_number = 2\nlisten_ip = \'0.0.0.0\'\nlisten_port = \'4337\'\nmax_connections = 800\nqueue_size = 200\npanic_on_new_connection = false\npanic_on_shutdown = false\nfragments_capacity = 100\nfragments_grow = true\nfragment_size = 65535\nin_buffer_capacity = 2048\nin_buffer_grow = true\nout_buffer_capacity = 2048\nout_buffer_grow = true\npanic_on_internal = true\npanic_on_capacity = false\npanic_on_protocol = false\npanic_on_encoding = false\npanic_on_queue = false\npanic_on_io = false\npanic_on_timeout = false\nshutdown_on_interrupt = true\nmasking_strict = false\nkey_strict = false\nmethod_strict = false\nencrypt_server = false\ntcp_nodelay = false\n\n[new_tx_flow_config]\ncount_per_batch = 30\nbuffer_duration = 30000000\n"
2018-02-15T23:50:57.340680519-06:00 - ERROR -
============================
stack backtrace:
   0:     0x55a4235487ec - backtrace::backtrace::trace::h253bc8b5b867400a
   1:     0x55a423548822 - backtrace::capture::Backtrace::new::h95e193ae7a0c60b0
   2:     0x55a42345b234 - panic_hook::panic_hook::hd081f29177483d0b
   3:     0x55a42345aef8 - core::ops::function::Fn::call::hd704e9c92e7d7362
   4:     0x55a4235a0d55 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   5:     0x55a4235a0b6e - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   6:     0x55a4235a0ada - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   7:     0x55a42351ef33 - pubsub_rabbitmq::start_rabbitmq::h175ce6fe58d57453
   8:     0x55a4232fda04 - pubsub::start_pubsub::h0337618a34bc4b92
   9:     0x55a42326e189 - cita_jsonrpc::main::h3204a7b2a895379a
  10:     0x55a4235b706e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:101
  11:     0x55a42359c2a3 - std::panic::catch_unwind<closure,()>
                        at /checkout/src/libstd/panicking.rs:459
                         - std::rt::lang_start
                        at /checkout/src/libstd/rt.rs:58
  12:     0x7fdfa4d8582f - __libc_start_main
  13:     0x55a4231c7838 - _start
  14:                0x0 - <unknown>

position:
Thread main panicked at failed to open url amqp://guest:guest@localhost/node0 : IoError(ConnectionRefused), /home/parallels/.cargo/git/checkouts/cita-common-1aad419f3e80ba17/b181fca/pubsub_rabbitmq/src/lib.rs:53

**Comment by zhangsoledad** [comment]
make sure you have installed `rabbitmq`, and run below script(maybe need sudo)
```shell
scripts/config_rabbitmq.sh
```
there should have better error message, we will improve it.
a better doc is in work in process.
Thanks for report.
