### ISSUE TITLE
Turn off Node Log 

### ISSUE THREAD

**Issue by willsays** [cryptape/cita#154]
Each node generated 4GB of log after 24hours of runtime, anyway to reduce or auto pruning it?

**Comment by zhangsoledad** [comment]
tool like `logrotate` can deal with your problem.
https://linux.die.net/man/8/logrotate
https://www.digitalocean.com/community/tutorials/how-to-manage-logfiles-with-logrotate-on-ubuntu-16-04

**Comment by janx** [comment]
@zhangsoledad @u2 I think we should have a cmd swtich/option to turn off logs or decrease log level.

**Comment by willsays** [comment]
thanks!
