### ISSUE TITLE
Rewrite config tool

### ISSUE THREAD

**Issue by zhangsoledad** [cryptape/cita#158]
位于`scripts/admintool`下的脚本工具，用于快速生成节点配置 [admintool](https://github.com/cryptape/cita/blob/v0.13/scripts/admintool/README.md) ，依赖`pyethereum`一些函数，引入了不必要的依赖，欠缺灵活性，在实际部署中也显得鸡肋，需要用rust来实现一个新的简单工具，实现
- [ ] 生成节点密钥对
- [ ] 生成 genesis.json

**Comment by janx** [comment]
Begin at Mar. 9th.

**Comment by TheWaWaR** [comment]
I can give a design of the command line interface.
