### ISSUE TITLE
6f4eaf7a: queryUsersOfPermission(uint8) error 

### ISSUE THREAD

**Issue by willsays** [cryptape/cita#160]
I was able to add the create permission to address c522a28a1d9709bd451b651376a23134b83a529.

And it works but when I look the permission using queryPermission  

```

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call",
"params":[{"to":"0x00000000000000000000000000000000013241a4",
"data":"0x54ad6352000000000000000000000000c522a28a1d9709bd451b651376a23134b83a5296"}, "0x6"],"id":2}' 127.0.0.1:1337 | jq 
```

it returns

```
{
  "jsonrpc": "2.0",
  "id": 2,
  "result": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

Think it means the address does not have the privilege to read nor create, it is a mistake or bug?

**Comment by u2** [comment]
Could you paste the transaction receipt?
