### ISSUE TITLE
Native executor

### ISSUE THREAD

**Issue by zbl2017** [cryptape/cita#163]
How can I run a native code on the cita? I mean, some codes like python, go, rust and etc. not solidity.
I find support on the document which says that support native executor, but I do not know how and I didn't see any support in the source code.

**Comment by EighteenZi** [comment]
Now contracts written in Rust, Go, Solidity are all available on CITA, and the new documents will come very soon.
Python is under considered.

**Comment by zbl2017** [comment]
Hoping the updated documents could coming very soon.
Or I can find some examples in the test folder.

**Comment by EighteenZi** [comment]
hi @zbl2017 , the following linkage descripes how to write smart contracts in Rust, and you can have a try.
https://cryptape.github.io/Nervos-AppChain-Docs/#/zh-CN/smart-contract/rust
