### ISSUE TITLE
Thread main panicked at failed to open url amqp://guest:guest@localhost/node/0

### ISSUE THREAD

**Issue by ijustgoon** [cryptape/cita#166]
Thread main panicked at failed to open url amqp://guest:guest@localhost/node/0 : Protocol("Unexpected method frame: connection.close, expected: connection.open-ok"), /opt/.cargo/git/checkouts/cita-common-1aad419f3e80ba17/e743a2a/pubsub_rabbitmq/src/lib.rs:53

**Comment by TheWaWaR** [comment]
Please check rabbitmq vhosts if `node/0` is in the list
```
sudo rabbitmqctl list_vhosts
```

**Comment by rink1969** [comment]
You should run ./bin/cita setup node/0 before start the node.
Or maybe you setup nodes concurrently. We just fix it https://github.com/cryptape/cita/commit/9e9c338dbc046aaed283e8b86e0c4ddcd6800f2b
So you can try the latest verison.
