### ISSUE TITLE
Better to kill cita-* process in cita_crosschain.sh for rerunning?

### ISSUE THREAD

**Issue by 3for** [cryptape/cita#167]
I've seen there's clean data code in cita/tests/integrate_test/cita_crosschain.sh, for rerun test, it would be better to add the kill the cita-* processes, such as:
```
for pid in cita-forever cita-jsonrpc cita-auth cita-chain cita-network cita-bft trans_evm cita-executor; do
        ps ax |grep ${pid}|awk '{print $1}' |xargs -n 1 -I %  kill -9 % 2>&1 >/dev/null ||true
done
```

**Comment by EighteenZi** [comment]
Instead of using the 'for' statement, you can use `pkill cita-` to kill all processes starting with 'cita-' with less words. And also `pkill trans_evm` will kill the process of the same name.
