### ISSUE TITLE
How can I communicate with the cita-chain using Remix

### ISSUE THREAD

**Issue by 3for** [cryptape/cita#168]
I want to know the detail configuration steps about how to communicate my contracts in Remix with the CITA-Chain.
I've tried using the default ethereum endpoint, but it doesn't work.
![image](https://user-images.githubusercontent.com/30716372/40823784-3de52596-65a4-11e8-83c6-37180ed4ebfa.png)

**Comment by EighteenZi** [comment]
@kaikai1024 , do we support debugging contracts in Remix?

**Comment by kaikai1024** [comment]
Please check the [remix-cita](https://github.com/CITA-Toys/remix-cita)

We haven’t deployed it yet. You can try it locally

**Comment by 3for** [comment]
Amazing~

**Comment by 3for** [comment]
I've got a problem while using remix-cita, detail info in [issue#1](https://github.com/CITA-Toys/remix-cita/issues/1).
Any help appreciated.
