### ISSUE TITLE
What's the main difference between block_gas_limit and account_gas_limit for CITA?

### ISSUE THREAD

**Issue by 3for** [cryptape/cita#171]
I'm not sure the main design principle for block_gas_limit and accout_gas_limit, in cita-common/libproto/src/protos/blockchain.proto and auth.proto. 
It seemed that there's no account gas limit in Ethereum.

Any help appreciated.

```
message BlockTxHashes {
    uint64 height = 1;
    repeated bytes tx_hashes = 2;
    uint64 block_gas_limit = 3;
    AccountGasLimit account_gas_limit = 4;
    bool check_quota = 5;
}
message AccountGasLimit {
    uint64 common_gas_limit = 1;
    map<string,uint64> specific_gas_limit = 2;
}
```

**Comment by driftluo** [comment]
Block_gas_limit: Decide the upper limit of transaction execution in one block.
Account_gas_limit: In relation to rights management, you can set the upper limit for a specific account, limiting it or expanding it
