### ISSUE TITLE
Question regarding Quota

### ISSUE THREAD

**Issue by miguelmota** [cryptape/cita#181]
The [whitepaper](https://github.com/cryptape/cita-whitepaper/blob/master/en/technical-whitepaper.md) mentions
> Native executor consumes quota as a realtime clock ticks

So that means that quota is how long a Nervos smart contract can run [in terms of seconds] (unlike the EVM where the gas limit is how many computational steps it can take)?

What happens if the time differs between miners (for example, quota is reached for one miner, but not the other miner because he has more compute resources)?

**Comment by janx** [comment]
Quota is an abstract metric of resources consumed in transaction processing, what it represents depends on the underlying executor. It's gas for evm contract, time for native contract.

As you pointed out, processing time can be differed on different nodes, which will cause consensus failure. In that case the system will lose liveness and requires some kind of intervention. Time difference won't cause correctness problem. We think it's acceptable in permissioned/consortium scenario, and leave it as an option to user.

**Comment by janx** [comment]
> So that mean that quota is how long a Nervos smart contract can run [in terms of seconds]

Didn't notice you mentioned Nervos. Just for clarification: Nervos CKB is NOT based on CITA, it's a new project. CITA/quota has nothing to do with CKB contracts.

**Comment by miguelmota** [comment]
@janx Thanks for the explanation. It seems that CITA is more analogous to HyperLedger than to Ethereum since it's meant to be used in a consortium based network. 

Also thanks for clarifying my misunderstanding. Where can I find out more information regarding CKB contracts? Are they similar to contracts in CITA?

**Comment by janx** [comment]
@miguelmota that's right, though CITA is more than Fabric: with the effort of Nervos AppChain (which is a layer 2 solution based on CITA), we want to make CITA work together with CKB.

regarding to CKB contract: check the cell model in CKB's whitepaper to grasp an idea. We're still working hard on more specific spec, will release more details soon. Thanks!

**Comment by miguelmota** [comment]
@janx looking forward to it!
