### ISSUE TITLE
Where are the comments?         # 这个开源版本，是不是故意把注释删了？

### ISSUE THREAD

**Issue by kt10** [cryptape/cita#189]
## Description

TBD

## Steps to Reproduce

Omit

## Versions

develop

## Additional Information

------------------Chinese--------------------

### 这个开源版本，是不是故意把注释删了？

**Comment by kt10** [comment]
### 注释、文档不健全，不利于社区发展。

**Comment by kt10** [comment]
你们有没有迁移到 rust 的 stable 版本开发的计划？

**Comment by kt10** [comment]
### 还有：
- 你们有没有迁移到 rust 的 stable 版本开发的计划？你们用的 nightly 特性，有些已经 stable 了，还有一些已被明确标记 deprecated（比如 select! 从 rust-1.32 开始）
- 数据结构的命名能不能规整一下？读你们的源码效率好低，比如下面这几个类似逻辑的东西，为啥不能整成统一的命名风格？
```
MiscellaneousReq    Miscellaneous
VerifyBlockReq        VerifyBlockResp
GetBlockTxn            BlockTxn
```

**Comment by zhouyun-zoe** [comment]
Thanks for your advice! We would not remove code comments for our open source project. Instead, we have been working on improving our code comments and docs all the time. 
It will be greatly helpful if you can specify which part of the code cannot be fully understood without comments or what kinds of docs we need to add for the community. So we can improve corresponding comments and docs asap.

**Comment by kt10** [comment]
#### 每个模块的核心结构体、其在的每个字段、其配套的方法，基本都没有什么备注，这还需要单独指出来～～！

**Comment by zhouyun-zoe** [comment]
> ### 还有：
> * 你们有没有迁移到 rust 的 stable 版本开发的计划？你们用的 nightly 特性，有些已经 stable 了，还有一些已被明确标记 deprecated（比如 select! 从 rust-1.32 开始）

We do have a update plan（from nightly to stable）and currently working on this.

**Comment by kt10** [comment]
我表述的可能有误。我指的是：这几个都是 'req -> resp' 的消息对，统一的命名风格，可以提高一点可读性。比如：
```
MiscellaneousReq MiscellaneousResp
VerifyBlockReq     VerifyBlockResp
BlockTxnReq        BlockTxnResp
```

**Comment by kt10** [comment]
你们有没有 gitter 之类的 IRC 渠道？方便实时请教一些问题

**Comment by u2** [comment]
https://github.com/cryptape/cita#contact-us

**Comment by kaikai1024** [comment]
Check #220 #219
