### ISSUE TITLE
executor log error

### ISSUE THREAD

**Issue by jeffreyji666** [cryptape/cita#190]
============================
stack backtrace:
   0:     0x55e1bee94d2c - backtrace::backtrace::trace::hfa99d66440780557
   1:     0x55e1bee93fa2 - <backtrace::capture::Backtrace as core::default::Default>::default::h4d3bf2e7afd53899
   2:     0x55e1bee94018 - backtrace::capture::Backtrace::new::h92a28e62d17e981a
   3:     0x55e1bee932c8 - panic_hook::panic_hook::h55dfb5afe5d6dd62
   4:     0x55e1bee93008 - core::ops::function::Fn::call::h69f2a83f466ea8ca
   5:     0x55e1bf215cb3 - std::panicking::rust_panic_with_hook::hd470ff3b3e7a1b18
                        at libstd/panicking.rs:480
   6:     0x55e1bf215819 - std::panicking::continue_panic_fmt::hf0cf39ae1e114602
                        at libstd/panicking.rs:390
   7:     0x55e1bf21577d - std::panicking::begin_panic_fmt::hfc5862442bd06bfc
                        at libstd/panicking.rs:345
   8:     0x55e1bea0c9fe - pubsub_rabbitmq::start_rabbitmq::he6c8371c0b59984b
   9:     0x55e1be9d6c92 - pubsub::start_pubsub::h581a16243424a36a
  10:     0x55e1bea0516b - cita_executor::main::h04c21ec32e368309
  11:     0x55e1be9f2d12 - std::rt::lang_start::{{closure}}::hd34a6701a77946b5
  12:     0x55e1bf2156b2 - std::rt::lang_start_internal::{{closure}}::h444bf05eb286eca1
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hb527d54965a8815a
                        at libstd/panicking.rs:310
  13:     0x55e1bf2258c9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  14:     0x55e1bf204df5 - std::panicking::try::h83b5294aab121d1a
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h15c1ea783c7910d5
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hcc3e9196a926118d
                        at libstd/rt.rs:58
  15:     0x55e1bea06663 - main
  16:     0x7fcd89c6eb96 - __libc_start_main
  17:     0x55e1be9ba359 - _start
  18:                0x0 - <unknown>

position:
Thread main panicked at failed to open url amqp://guest:guest@localhost/test-chain/0 : IoError(AddrNotAvailable), /opt/.cargo/git/checkouts/cita-common-1aad419f3e80ba17/1b308bc/pubsub_rabbitmq/src/lib.rs:59

**Comment by keroro520** [comment]
This error cause when CITA cannot connect to RabbitMQ. So check whether RabbitMQ is already started.

Recommend that use the operate scripts `scripts/cita`(`target/install/bin/cita` instead after `make debug` or `make release`) to start CITA node, which would make sure RabbitMQ started.

Getting started document: https://docs.nervos.org/cita/#/getting_started

**Comment by jeffreyji666** [comment]
I run the CITA nodes and RabbitMQ within the same server.

**Comment by ouwenkg** [comment]
CITA is multiple microservices architecture system, nodes comminicate using RabbitMq. So, you need run 
`./bin/cita setup test-chain/0` firstly, and then `./bin/cita start test-chain/0`

**Comment by kaikai1024** [comment]
More details please. cita version, the operation etc.

**Comment by jeffreyji666** [comment]
I have already rebuilt the cluster,  the CITA docker image is: cita/cita-run:ubuntu-18.04-20180813, what I remember is the server run Microscope, re-brith and 4 CITA docker containers.  CPU load is very high.

**Comment by rink1969** [comment]
> Dude, I run 4 docker containers by docker-compose, the cluster had been running well for almost a week, but this issue happened suddenly.

Did you use docker-compose follow https://docs.nervos.org/cita/#/getting_started?id=docker-compose-quick-start?

The panic info show that error appeared when executor init, so I don't think it is happened suddenly after a week. 

Could you supply the cmd history before this issue happen?

**Comment by rink1969** [comment]
> I have already rebuilt the cluster, the CITA docker image is: cita/cita-run:ubuntu-18.04-20180813, what I remember is the server run Microscope, re-brith and 4 CITA docker containers. CPU load is very high.

I think the cita version is v0.19 or before. 

It is recommended that use the latest version. https://github.com/cryptape/cita/releases/tag/v0.20.2

**Comment by jeffreyji666** [comment]
> > Dude, I run 4 docker containers by docker-compose, the cluster had been running well for almost a week, but this issue happened suddenly.
> 
> Did you use docker-compose follow https://docs.nervos.org/cita/#/getting_started?id=docker-compose-quick-start?
> 
> The panic info show that error appeared when executor init, so I don't think it is happened suddenly after a week.
> 
> Could you supply the cmd history before this issue happen?

Yes, I Used the docker-compose by following the get started guide. and the cluster is running for more than a week.

I didn't run command but invoked the appchainj API through java application, like invoking smart contract, transaction.

**Comment by rainchen** [comment]
what is the appchainj version you're using, did you lock the version? It might be a compatibility problem.

**Comment by jeffreyji666** [comment]
This issue never happened again. It could be closed.
