### ISSUE TITLE
another bug

### ISSUE THREAD

**Issue by jeffreyji666** [cryptape/cita#191]
2018-12-26T12:58:14.695413766+00:00 - ERROR -
============================
stack backtrace:
   0:     0x55c38577946c - backtrace::backtrace::trace::hfa99d66440780557
   1:     0x55c3857786e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h4d3bf2e7afd53899
   2:     0x55c385778758 - backtrace::capture::Backtrace::new::h92a28e62d17e981a
   3:     0x55c385777a08 - panic_hook::panic_hook::h55dfb5afe5d6dd62
   4:     0x55c385777748 - core::ops::function::Fn::call::h69f2a83f466ea8ca
   5:     0x55c385ae47e3 - std::panicking::rust_panic_with_hook::hd470ff3b3e7a1b18
                        at libstd/panicking.rs:480
   6:     0x55c385ae4349 - std::panicking::continue_panic_fmt::hf0cf39ae1e114602
                        at libstd/panicking.rs:390
   7:     0x55c385ae4245 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x55c385b2a92b - core::panicking::panic_fmt::hf53111ba26d35bb0
                        at libcore/panicking.rs:77
   9:     0x55c38551dfe8 - core::result::unwrap_failed::hf395bb686c368e81
  10:     0x55c3854f84a3 - cita_chain::main::h0f9ea20d587582a3
  11:     0x55c3854f4252 - std::rt::lang_start::{{closure}}::hc641f19ed944e557
  12:     0x55c385ae41e2 - std::rt::lang_start_internal::{{closure}}::h444bf05eb286eca1
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hb527d54965a8815a
                        at libstd/panicking.rs:310
  13:     0x55c385af43f9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  14:     0x55c385ad6585 - std::panicking::try::h83b5294aab121d1a
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h15c1ea783c7910d5
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hcc3e9196a926118d
                        at libstd/rt.rs:58
  15:     0x55c3854f8643 - main
  16:     0x7ff40295bb96 - __libc_start_main
  17:     0x55c3854e19b9 - _start
  18:                0x0 - <unknown>

position:
Thread main panicked at called `Result::unwrap()` on an `Err` value: "Invalid argument: You have to open all column families. Column families not opened: col6, col1, col0, col2, col3, col4, col5", libcore/result.rs:1009

...skipping...
stack backtrace:
   0:     0x55cfa754d46c - backtrace::backtrace::trace::hfa99d66440780557
   1:     0x55cfa754c6e2 - <backtrace::capture::Backtrace as core::default::Default>::default::h4d3bf2e7afd53899
   2:     0x55cfa754c758 - backtrace::capture::Backtrace::new::h92a28e62d17e981a
   3:     0x55cfa754ba08 - panic_hook::panic_hook::h55dfb5afe5d6dd62
   4:     0x55cfa754b748 - core::ops::function::Fn::call::h69f2a83f466ea8ca
   5:     0x55cfa78b87e3 - std::panicking::rust_panic_with_hook::hd470ff3b3e7a1b18
                        at libstd/panicking.rs:480
   6:     0x55cfa78b8349 - std::panicking::continue_panic_fmt::hf0cf39ae1e114602
                        at libstd/panicking.rs:390
   7:     0x55cfa78b8245 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x55cfa78fe92b - core::panicking::panic_fmt::hf53111ba26d35bb0
                        at libcore/panicking.rs:77
   9:     0x55cfa72f1fe8 - core::result::unwrap_failed::hf395bb686c368e81
  10:     0x55cfa72cc4a3 - cita_chain::main::h0f9ea20d587582a3
  11:     0x55cfa72c8252 - std::rt::lang_start::{{closure}}::hc641f19ed944e557
  12:     0x55cfa78b81e2 - std::rt::lang_start_internal::{{closure}}::h444bf05eb286eca1
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hb527d54965a8815a
                        at libstd/panicking.rs:310
  13:     0x55cfa78c83f9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  14:     0x55cfa78aa585 - std::panicking::try::h83b5294aab121d1a
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h15c1ea783c7910d5
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hcc3e9196a926118d
                        at libstd/rt.rs:58
  15:     0x55cfa72cc643 - main
  16:     0x7ffb8966ab96 - __libc_start_main
  17:     0x55cfa72b59b9 - _start
  18:                0x0 - <unknown>

position:
Thread main panicked at called `Result::unwrap()` on an `Err` value: "Invalid argument: You have to open all column families. Column families not opened: col6, col1, col0, col2, col3, col4, col5", libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/cryptape/cita/issues/new

============================

**Comment by rink1969** [comment]
The cause of this is probably a corrupt database,  it caused by 'no space on disk' or 'suddenly shundown the power'.

**Comment by jeffreyji666** [comment]
Gotcha. It could be closed.
