### ISSUE TITLE
executor crash in first run

### ISSUE THREAD

**Issue by ijustgoon** [cryptape/cita#193]
## Description

executor crash:

2018-12-28T17:27:00.372430279+08:00 - INFO - CITA:executor
2018-12-28T17:27:00.372503548+08:00 - INFO - Version: v0.20.2
2018-12-28T17:27:00.415560234+08:00 - INFO - Session initialized
2018-12-28T17:27:00.463513954+08:00 - INFO - Session initialized
2018-12-28T17:27:00.628091248+08:00 - INFO - executor config: Config { prooftype: 2, journaldb_type: "archive", grpc_port: 5000 }
2018-12-28T17:27:01.763420054+08:00 - ERROR - 
stack backtrace:
   0:     0x55f3fa599f15 - backtrace::backtrace::libunwind::trace::h5e7b0bd5ede73dca
                        at /home/lyc/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h3c03c3417586eb2a
                        at /home/lyc/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x55f3fa593d4e - backtrace::capture::Backtrace::new_unresolved::h5880adc32c453849
                        at /home/lyc/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/backtrace-0.3.9/src/capture.rs:88
   2:     0x55f3fa593cac - backtrace::capture::Backtrace::new::hdd880a81f348c4e0
                        at /home/lyc/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/backtrace-0.3.9/src/capture.rs:63
   3:     0x55f3fa5925a8 - panic_hook::panic_hook::h68196299094b0877
                        at /home/lyc/.cargo/git/checkouts/cita-common-1aad419f3e80ba17/1b308bc/panic_hook/src/lib.rs:51
   4:     0x55f3fa592b47 - core::ops::function::Fn::call::h84ae58b1e3c254c4
                        at libcore/ops/function.rs:78
   5:     0x55f3fb017b43 - std::panicking::rust_panic_with_hook::hd470ff3b3e7a1b18
                        at libstd/panicking.rs:480
   6:     0x55f3fb0176a9 - std::panicking::continue_panic_fmt::hf0cf39ae1e114602
                        at libstd/panicking.rs:390
   7:     0x55f3fb0175a5 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x55f3fb05e33b - core::panicking::panic_fmt::hf53111ba26d35bb0
                        at libcore/panicking.rs:77
   9:     0x55f3fb05e26a - core::panicking::panic::h1b11496bce256cfc
                        at libcore/panicking.rs:52
  10:     0x55f3f9a1a8b4 - core_executor::libexecutor::executor::Executor::build_last_hashes::h5ab1efcf40b0554e
                        at cita-executor/core/src/libexecutor/executor.rs:486
  11:     0x55f3f9a1bef9 - core_executor::libexecutor::executor::Executor::call::hbd1af34da45e326d
                        at cita-executor/core/src/libexecutor/executor.rs:599
  12:     0x55f3f9a1b849 - core_executor::libexecutor::executor::Executor::eth_call::hacd192f94f3eed72
                        at cita-executor/core/src/libexecutor/executor.rs:569
  13:     0x55f3f9a17bf6 - <core_executor::libexecutor::executor::Executor as core_executor::contracts::solc::ContractCallExt>::call_method::h8e32db86b0835862
                        at cita-executor/core/src/contracts/solc/mod.rs:72
  14:     0x55f3f988b191 - core_executor::contracts::solc::node_manager::NodeManager::nodes::h1d9e56cc29d33817
                        at cita-executor/core/src/contracts/solc/node_manager.rs:78
  15:     0x55f3f988b491 - core_executor::contracts::solc::node_manager::NodeManager::stake_nodes::ha9df712a34d8ef78
                        at cita-executor/core/src/contracts/solc/node_manager.rs:114
  16:     0x55f3f988b306 - core_executor::contracts::solc::node_manager::NodeManager::shuffled_stake_nodes::hc092801cf1f0bc37
                        at cita-executor/core/src/contracts/solc/node_manager.rs:102
  17:     0x55f3f9a1ef99 - core_executor::libexecutor::executor::Executor::load_config::h686b7372edef0235
                        at cita-executor/core/src/libexecutor/executor.rs:815
  18:     0x55f3f9a1914f - core_executor::libexecutor::executor::Executor::init_executor::hb473eb98c6e145e5
                        at cita-executor/core/src/libexecutor/executor.rs:322
  19:     0x55f3f9769d04 - cita_executor::executor_instance::ExecutorInstance::new::hfd5aac517c96a3ea
                        at cita-executor/src/executor_instance.rs:83
  20:     0x55f3f971f9df - cita_executor::main::hb198fb6b2b5baca1
                        at cita-executor/src/main.rs:159
  21:     0x55f3f973f93f - std::rt::lang_start::{{closure}}::h25cb38f66fbda4a4
                        at libstd/rt.rs:74
  22:     0x55f3fb017542 - std::rt::lang_start_internal::{{closure}}::h444bf05eb286eca1
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hb527d54965a8815a
                        at libstd/panicking.rs:310
  23:     0x55f3fb027759 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  24:     0x55f3fb006c65 - std::panicking::try::h83b5294aab121d1a
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h15c1ea783c7910d5
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hcc3e9196a926118d
                        at libstd/rt.rs:58
  25:     0x55f3f973f917 - std::rt::lang_start::h843cdae6dd764c0d
                        at libstd/rt.rs:74
  26:     0x55f3f971ffb9 - main
  27:     0x7fbef30afb96 - __libc_start_main
  28:     0x55f3f9715a79 - _start
  29:                0x0 - <unknown>

position:
Thread main panicked at attempt to subtract with overflow, cita-executor/core/src/libexecutor/executor.rs:486

## Versions
V0.20.2

**Comment by kaikai1024** [comment]
Check this commit:

https://github.com/cryptape/cita/commit/69141868436cbd17c4b45a8ba5145d7adaf1915f

**Comment by ouwenkg** [comment]
Sorry, That is a bug in this version. we had fixed it in the next release version.

**Comment by rink1969** [comment]
It's my fault.
v0.20.2 is a hot fix version.
After I fixed the critical bug, this bug appeared.
But I test with release build, subtract overflow won't crash in release build. So it was ignored.

You can workround this bug with release build.
Or use the develop branch, where it has fixed.
