### ISSUE TITLE
getFilterChanges returns current block instead of next block

### ISSUE THREAD

**Issue by Keith-CY** [cryptape/cita#200]
**Expected behavior**: [What you expect to happen]

I created a new block filter at height of 3000, and get changes of the filter, it's expected to get block at  height of 3001

**Actual behavior**: [What actually happens]

Block at height of 3000 returned.

## Versions

v0.20

**Comment by ouwenkg** [comment]
Does this issue exist in the latest version?

**Comment by ouwenkg** [comment]
After some exploration, I found out that the original logic is like this.
The return value of getFilterChanges include the 3000 block  @Keith-CY 
[https://github.com/cryptape/cita/blob/develop/cita-chain/core/src/filters/eth_filter.rs#L58-L68](url)

**Comment by kaikai1024** [comment]
> After some exploration, I found out that the original logic is like this.
> The return value of getFilterChanges include the 3000 block @Keith-CY
> [https://github.com/cryptape/cita/blob/develop/cita-chain/core/src/filters/eth_filter.rs#L58-L68](url)

Can you fix it on cita-sdk-js?

**Comment by kaikai1024** [comment]
Add some descriptions on doc.

**Comment by kaikai1024** [comment]
I think it’s better to fix it at rpc module of cita.

**Comment by Keith-CY** [comment]
> I think it’s better to fix it at rpc module of cita. @ouwenkg

Agree, not everyone uses sdk to get filter logs

**Comment by ouwenkg** [comment]
Get it, fix it today.

**Comment by ouwenkg** [comment]
None！
