### ISSUE TITLE
Ordinary nodes can't sync blocks case of different result when executing a tx.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#201]
## Description

Ordinary nodes can't sync blocks cause of different result when executing a tx.

## Steps to Reproduce

1. Create a new group from the rootGroup: groupA
2. Grant a permission to the GroupA: sendTx 
3. Add a new account to the GroupA; userA
4. UserA send a transaction and it is blocked at next height.
5. ordinary sync the blocks

**Expected behavior**: ordinary can sync the blocks to the latest.

**Actual behavior**: Stop at a height

**Reproduce how often**: Once

## Versions

0.19

## Additional Information

=============Chinese==============
版本： 0.19

描述： 共识节点执行一条交易结果为 No send transaction permission，而同步节点执行时通过，导致块验证不过，无效。停止同步

触发场景（待复现）： 使用用户管理系统合约，步骤如下：

1. 从 rootGroup 下新建一个 groupA
2. 赋予 groupA 一个权限，比如： sendTx
3. 发交易向 groupA 添加一个用户: UserA
4. UserA发送交易，并且交易精确的在下一个高度被打包进块
5. 同步节点从此交易之前的块开始同步

**Comment by yangby-cryptape** [comment]
Simply stated, the height which was used to reload the system configuration ([`get_sys_config()`]) when synchronizing blocks is greater than when producing blocks in the normal way.

### Details

1. [`execute_proposal()`] when producing blocks in the normal way:
   https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L968-L972
2. [`execute_block()`] when synchronizing blocks:
   https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L931-L935
3. In above pieces of codes. Both of them call [`get_max_height()`] to reload the system configuration ([`get_sys_config()`]).
   https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L362-L376
4. When producing blocks in the normal way, the max height will always be current height in almost all scenes.
   But when synchronizing blocks, the max height will be the max height it gets from network, it will be greater than the current height until all blocks behind it was executed.
   So this line in [`get_sys_config()`] can not work correctly (`now_height` is greater than the current height):
   https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L367

### How to fix it

I think, use [`get_current_height()`] to replace those [`get_max_height()`] in above can fix this bug.

[`execute_proposal()`]: https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L968-L972
[`execute_block()`]: https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L931-L935
[`get_max_height()`]: https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L432-L434
[`get_current_height()`]:
https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L424-L426
[`get_sys_config()`]: https://github.com/cryptape/cita/blob/17cb35a017287a8f0610c862d7fa432991155c22/cita-executor/core/src/libexecutor/executor.rs#L362-L376

**Comment by kaikai1024** [comment]
We will release a patch version of 0.19.

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita/releases/tag/v0.19.1

TODO: Add a  integrate test

**Comment by u2** [comment]
https://github.com/cryptape/cita/commit/e60a0888dc87a8494449eeab7b50c6c37e0b2a34
