### ISSUE TITLE
Do we need a cita_play image?

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#202]
## Description

A full image including all the dependent parts of CITA. You can play CITA using this image without other operation. such as TiDB of PinCap.

Now we need to pull the cita_build after we git clone the code if we want to use the latest branch.
Pull the cita_run image to run the CITA if we use the  release version.

## Additional Information

-------------------Chinese--------------

我们是否需要一个开箱即用的镜像？目前的情况是如果我们用最新的 develop 分支，就得拉取 cita_build 镜像编译，如果想要使用发布版，需要拉取 cita_run 镜像运行

**Comment by leeyr338** [comment]
Yes, we need it!
We need to release that image which has fully tested.

**Comment by rainchen** [comment]
+1, and I prefer `cita` than `cita-run` as the docker image name

**Comment by kaikai1024** [comment]
`env.sh` and `daemon.sh` are not friendly for users. It's ok for developer, not users. Users will be confused.

**Comment by kaikai1024** [comment]
@ouwenkg

**Comment by ouwenkg** [comment]
Yeap， I had been bothered by `env.sh` or `daemon.sh` for a long time. If you start your node use command `.env.sh ./bin/cita start test-chain/*`,  node processes does not start and no error msg. That so terrible for users or external developer.
