### ISSUE TITLE
Start CITA after bench.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#207]
## Description

bench before staring CITA.

## Steps to Reproduce

1. bench
2. start CITA

**Expected behavior**: Works normal

**Actual behavior**: Some modules do not work

**Reproduce how often**: occasionally

## Additional Information

------------------Chinese---------------------

先开启压测，往 jsonrpc 尝试死命发交易，然后再起链，有概率个别服务工作不正常

**Comment by leeyr338** [comment]
Would you please show me the exactly commands of your steps?

**Comment by kaikai1024** [comment]
Use our bench tool to send tx first(Always send transactions), then start the chain.
