### ISSUE TITLE
Rename emergency brake

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#208]
## Description

Rename emergency brake.

## Versions

develop

## Additional Information

------------------Chinese--------------------

`emergency intervention`，这个词应该更好

https://dictionary.reverso.net/english-definition/emergency+intervention

https://en.wikipedia.org/wiki/Emergency_brake

`emergency_brake` 这个词用在紧急刹车方面的，物理的

**Comment by keroro520** [comment]
I use `emergency_unlocker` in Auth 2.0.

**Comment by kaikai1024** [comment]
> I use `emergency_unlocker` in Auth 2.0.

unlock the emergency mode?

**Comment by u2** [comment]
https://translate.google.com/?um=1&ie=UTF-8&hl=en&client=tw-ob#view=home&op=translate&sl=auto&tl=en&text=%E7%B4%A7%E6%80%A5%E5%B9%B2%E9%A2%84

**Comment by keroro520** [comment]
> > I use `emergency_unlocker` in Auth 2.0.
> 
> unlock the emergency mode?

地铁上紧急制动栓上有 unlocker 字样，我是从那儿来的灵感。
我这么理解，紧急制动的情况下，只有 unlocker 能打开这个局面 :D

**Comment by kaikai1024** [comment]
> > > I use `emergency_unlocker` in Auth 2.0.
> > 
> > 
> > unlock the emergency mode?
> 
> 地铁上紧急制动栓上有 unlocker 字样，我是从那儿来的灵感。
> 我这么理解，紧急制动的情况，也就是系统被锁住了，只有 unlocker 能打开这个局面 :D

这个开关打开才是 紧急制动……

**Comment by u2** [comment]
这个问题是这样，当这个词给外面客户介绍时，比如对面是金融/政府部门，在这两个场合英语用的是intervention，这个应该是专有名词。而这个功能本意，也是因为他们想要的“干预”。而“紧急”这个词只是我们增加的修饰而已。

**Comment by keroro520** [comment]
> > > > I use `emergency_unlocker` in Auth 2.0.
> > > 
> > > 
> > > unlock the emergency mode?
> > 
> > 
> > 地铁上紧急制动栓上有 unlocker 字样，我是从那儿来的灵感。
> > 我这么理解，紧急制动的情况，也就是系统被锁住了，只有 unlocker 能打开这个局面 :D
> 
> 这个开关打开才是 紧急制动……

嗯，我知道。
我只是参考了地铁上的紧急制动栓的英文，将这个变量比作紧急制动栓而已。
具体，我觉得都可以，能让人意会即可。

**Comment by kaikai1024** [comment]
> > > > > I use `emergency_unlocker` in Auth 2.0.
> > > > 
> > > > 
> > > > unlock the emergency mode?
> > > 
> > > 
> > > 地铁上紧急制动栓上有 unlocker 字样，我是从那儿来的灵感。
> > > 我这么理解，紧急制动的情况，也就是系统被锁住了，只有 unlocker 能打开这个局面 :D
> > 
> > 
> > 这个开关打开才是 紧急制动……
> 
> 嗯，我知道。
> 我只是参考了地铁上的紧急制动栓的英文，将这个变量比作紧急制动栓而已。
> 具体，我觉得都可以，能让人意会即可。

很有创意。
我自己更倾向于意思更确定的词，我试着搜了一下这个的翻译，还搜到了一个 软件的名称 ，破解的意思。我一下子没联想到地铁的紧急制动栓……

**Comment by rainchen** [comment]
软件架构上有个 熔断机制（Circuit Breaker），用来防止雪崩效应
例如：
https://github.com/Netflix/Hystrix/wiki/Configuration#CommandCircuitBreaker
