### ISSUE TITLE
Integrate the ethereum tests

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#222]
## Description

https://github.com/ethereum/tests

## Versions

develop

## Additional Information

------Chinese-------

集成 [ethereum tests](https://github.com/ethereum/tests) 的测试用例

**Comment by kaikai1024** [comment]
That's the main purpose of this version.
You can focus on this. @ouwenkg

**Comment by ouwenkg** [comment]
Ok， I will do some research work firstly.

**Comment by kaikai1024** [comment]
must-have: evm
better-have: others.

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita-vm

**Comment by kaikai1024** [comment]
Create a new issue about evm tests and refer here. @ouwenkg
