### ISSUE TITLE
Consensus stopped when testing snapshot ### 测试备份恢复及同步功能时无法正常出块

### ISSUE THREAD

**Issue by luqz** [cryptape/cita#226]
节点备份恢复后进行同步，无法正常出块

## Steps to Reproduce

1. 设置四个节点并启动运行链；
2. 在高度不超过100时对节点0使用snapshot_tool进行备份；
3. 停止1，2，3三个节点的运行并清空数据；
4. 在节点0恢复备份数据，停止该节点运行；
5. 重新启动节点0，1，2，3（其中节点3在节点1，2同步完成后再启动）；

**Expected behavior**: 所有节点正常出块

**Actual behavior**: 所有节点同步到相同高度后不继续出块

**Reproduce how often**: 几乎每次

## Versions

[The versions of the CITA, operating systems or VM software you use]
CITA: v0.21pre
systems: Ubuntu18.04

## Additional Information

若不执行第4步的恢复操作，大部分时候可以正常运行，偶尔也会出现无法继续出块的情况

**Comment by ouwenkg** [comment]
Thanks for your issue! We will reproduce this problem as soon as possible to determine if there is a bug in the snapshot module. Please continue to pay attention.

**Comment by kaikai1024** [comment]
Check if it's a bug @ouwenkg

**Comment by ouwenkg** [comment]
ok

**Comment by keroro520** [comment]
Have been reproduced via script below, which is modified `tests/integrate_test/cita_snapshot_test.sh`: https://gist.github.com/keroro520/aeda08ee0b14b9e18087c51026ae1dc2

I try to explain the reason why this occurs:

1. All nodes' `data/wal` losing will cause stopping growing up:
    * cita-bft would dump its current ballot state into `data/wal`.
    * Every time node starts, cita-bft, as consensus component, loads `data/wal` and treats it as the current ballot state.
    * If cita-bft cannot find its `data/wal`, it will wait other proposer's vote and use that as it's current ballot state.
    * Bad thing is that, when all nodes lost their `data/wal` and restart, all nodes wait others' votes. Dead lock happened. All nodes stop growing up.

2. Restoring snapshot will remove `data/wal`
    * cita-bft removes `data/wal` during restoring snapshot: https://github.com/cryptape/cita-bft/blob/develop/src/core/cita_bft.rs#L1746-L1758

So, node-0's `data/wal` has been removed during restoring snapshot, node-{1,2,3}'s `data/wal` by cleanup manually. Restarting nodes cannot grow up anymore.

**Comment by kaikai1024** [comment]
> Have been reproduced via script below, which is modified `tests/integrate_test/cita_snapshot_test.sh`: https://gist.github.com/keroro520/aeda08ee0b14b9e18087c51026ae1dc2
> 
> I try to explain the reason why this occurs:
> 
> 1. All nodes' `data/wal` losing will cause stopping growing up:
>    
>    * cita-bft would dump its current ballot state into `data/wal`.
>    * Every time node starts, cita-bft, as consensus component, loads `data/wal` and treats it as the current ballot state.
>    * If cita-bft cannot find its `data/wal`, it will wait other proposer's vote and use that as it's current ballot state.
>    * Bad thing is that, when all nodes lost their `data/wal` and restart, all nodes wait others' votes. Dead lock happened. All nodes stop growing up.
> 2. Restoring snapshot will remove `data/wal`
>    
>    * cita-bft removes `data/wal` during restoring snapshot: https://github.com/cryptape/cita-bft/blob/develop/src/core/cita_bft.rs#L1746-L1758
> 
> So, node-0's `data/wal` has been removed during restoring snapshot, node-{1,2,3}'s `data/wal` by cleanup manually. Restarting nodes cannot grow up anymore.

Cool. Do you have some suggestions to deal with this situation?

**Comment by keroro520** [comment]
@luqz @kaikai1024 I have no any solution. 

cita-bft strongly rely on `data/wal`, maybe we should find a better way to this (reload current ballot state). cc @jerry-yu

**Comment by jerry-yu** [comment]
The point is step 4. In my opinion,there are bugs at snapshot recovering

**Comment by kaikai1024** [comment]
Maybe we can add some attention docs first。

**Comment by jerry-yu** [comment]
done
