### ISSUE TITLE
mac append node not generate address

### ISSUE THREAD

**Issue by 77liyan** [cryptape/cita#227]
# Issue Template

## Description

[mac append node not generate address, in ubuntu append after can generate address  ]

## Steps to Reproduce

1.    
 ./env.sh ./scripts/create_cita_config.py create --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"  --super_admin 0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523 --contract_arguments SysConfig.economicalModel=1

2. l**s test-chain/0**             Check the generated address

3.  **./scripts/create_cita_config.py append --chain_name test-chain --node "127.0.0.1:4004"**
The output：  sh: /Users/yanli/soft/CITA/Test/cita_secp256k1_sha3/bin/create_key_addr: cannot execute binary file

4.  **ls  test-chain/4**         The test found no generated address

**Expected behavior**: [append node generated address]

**Actual behavior**: [mac append node generated address,  
 sh: /Users/yanli/soft/CITA/Test/cita_secp256k1_sha3/bin/create_key_addr: cannot execute binary file]

**Reproduce how often**: [every time]

## Versions

[http://ci.engpro.cryptape.com:8080/job/build-cita-release/35/artifact/cita_secp256k1_sha3.tar.gz]

**Comment by keroro520** [comment]
Step 3 change to (add prefix `./env.sh `)

```
./env.sh ./scripts/create_cita_config.py append --chain_name test-chain --node "127.0.0.1:4004"
``` 

and retry ?

**Comment by 77liyan** [comment]
> Step 3 change to (add prefix `./env.sh `)
> 
> ```
> ./env.sh ./scripts/create_cita_config.py append --chain_name test-chain --node "127.0.0.1:4004"
> ```
> and retry ?

it can generate address and not error remind

**Comment by ouwenkg** [comment]
Done！
