### ISSUE TITLE
本机起链，一次多节点，不出块

### ISSUE THREAD

**Issue by mingxiaowu** [cryptape/cita#228]
# Issue Template
本机起链，一次多节点，不出块
## Description

[Description of the issue]

## Steps to Reproduce
场景：起链时，启动多个节点
1. 一次启动10个节点，成功出块；
2. 一次启动 大于等于20节点，不出块。

**Expected behavior**: [What you expect to happen]

**Actual behavior**: [What actually happens]

**Reproduce how often**: [What percentage of the time does it reproduce?]

## Versions

[The versions of the CITA, operating systems or VM software you use]

## Additional Information

[Any other information which would be helpful to reproduce the issue].

**Comment by ouwenkg** [comment]
For a single machine, start 20 nodes at the same time takes up too much resources, which can cause problem.
