### ISSUE TITLE
body of getBlock don't return from address in v0.21rc

### ISSUE THREAD

**Issue by classicalliu** [cryptape/cita#229]
## Description

`getTransaction` returns `from` address in v0.21rc, but body of `getBlockByNumber` does not.

## Versions

v0.21rc

## Additional Information

`getTransaction`

![image](https://user-images.githubusercontent.com/13375784/52770388-e864cf00-306d-11e9-8c95-f111c3c4c42f.png)

`getBlockByNumber`

![image](https://user-images.githubusercontent.com/13375784/52770412-f74b8180-306d-11e9-828b-6ce482b18355.png)

**Comment by kaikai1024** [comment]
I will check that ASAP.

**Comment by kaikai1024** [comment]
@classicalliu 

You can try to resolve this issue by yourself. you can refer to the [commit](https://github.com/cryptape/cita-common/commit/f85faf2bd8169c57e143b00b500e90a4fa3e80c3)

**Comment by classicalliu** [comment]
OK, I'll try

**Comment by kaikai1024** [comment]
> OK, I'll try

Cool

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita-common/commit/f85faf2bd8169c57e143b00b500e90a4fa3e80c3

**Comment by kaikai1024** [comment]
You can continue to update cita-common submodule. @classicalliu
