### ISSUE TITLE
Is it possible to use in CITA our altcoin?

### ISSUE THREAD

**Issue by alexpro401** [cryptape/cita#23]
Hello, excellent concept of the blockchain, please tell us possible the implementation of our altcoin in the platform?

**Comment by suyanlong** [comment]
Is the installation Guide？

**Comment by alexpro401** [comment]
If there is a guide for installing creating our altcoin in CITA it would be excellent.

**Comment by suyanlong** [comment]
altcoin? you want to creat coin in CITA?

**Comment by alexpro401** [comment]
Yes it is possible?

**Comment by suyanlong** [comment]
sorry.

**Comment by janx** [comment]
@alexpro401 although there's no built-in economics in CITA, it's possible.

For an altcoin, you may want ordinary user to run it on their laptop more conveniently, without enterprise-level queue. A simple in-memory queue may fit better.
