### ISSUE TITLE
Set eth_compatibility = true to timestamp with second not take effect in cita-cli  

### ISSUE THREAD

**Issue by 77liyan** [cryptape/cita#230]
## Description

[Set eth_compatibility = true to timestamp with second not take effect in cita-cli  ]

## Steps to Reproduce

1.   **GetTime.sol**
`pragma solidity ^0.4.24;
contract SimpleTest {
function getTime() public constant returns (uint retVal){
return now;
}
}`

2. **create contract and  call getTime()** 
**output:**
**"blockNumber": "0x1e"**

`rpc call --to 0x27ec3678e4d61534ab8a87cf8feb8ac110ddeda5 --data 0x557ed1ba`
**output:**
`{
  "id": 1,
  "jsonrpc": "2.0",
  "result": "0x000000000000000000000000000000000000000000000000000000005c6540c6"
}`
printf "%d" 0x005c6540c6
**output:**   1550139590
**check result 10 digit** 

3.  but execute
`rpc getBlockByNumber --height 0x1e` 
**output:** 
`"timestamp": 1550139557545, .......` 
**check result 13 digit** 

**Expected behavior**:   expect to step 3 timestamp result 10 digit  with second 

**Actual behavior**:  actually  step 3 timestamp result 13 digit  with millisecond

**Reproduce how often**: every time

## Versions
Version: v0.21rc
Commit id：f24e690
Branch：https://github.com/cryptape/cita/tree/v0.21pre

[http://ci.engpro.cryptape.com:8080/job/build-cita-release/35/artifact/cita_secp256k1_sha3.tar.gz]

**Comment by ouwenkg** [comment]
In the Ethereum-compatible timestamp mode, the timestamp returned in the getBlockByNumber interface is still in milliseconds. Please check if there is a problem here. @rink1969

**Comment by ouwenkg** [comment]
Guys, This is a normal phenomenon. This task is mainly for the time precision of compatible contract process, which is evm level, and have nothing to do with block-level time precision. We don't have to be compatible with Eth in block structure. @77liyan

**Comment by u2** [comment]
This feature only affects the EVM, it's not a bug. The block timestamp is always the millisecond.
