### ISSUE TITLE
Compatibility test

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#238]
## Description

TBD

## Steps to Reproduce

Omit

## Versions

develop

## Additional Information

-----------------Chinese----------------

兼容性测试

**Comment by kaikai1024** [comment]
* 对上个版本的兼容
* 对上个协议版本的兼容

**Comment by kaikai1024** [comment]
@yangby-cryptape

**Comment by yangby-cryptape** [comment]
Since the test team has their own management style, I added those test scenes in their task list.

Close this issue?

**Comment by kaikai1024** [comment]
> Since the test team has their own management style, I added those test scenes in their task list.
> 
> Close this issue?

Keep it. we need our own test, too

**Comment by kaikai1024** [comment]
#223
