### ISSUE TITLE
Specify the path to of data and log.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#243]
## Description

Specify the path to of data and log.

## Steps to Reproduce

Omit

## Versions

develop

## Additional Information

----------------Chinese-------------

可指定 log 和 data 文件夹的路径

**Comment by kaikai1024** [comment]
#221

**Comment by leeyr338** [comment]
Has  someone work on this issue?

**Comment by u2** [comment]
> Has someone work on this issue?

If you have more time, can you help with this task https://github.com/cryptape/cita-common/issues/177.

**Comment by kaikai1024** [comment]
> Has someone work on this issue?

I will.

**Comment by kaikai1024** [comment]
> > Has someone work on this issue?
> 
> If you have more time, can you help with this task [cryptape/cita-common#177](https://github.com/cryptape/cita-common/issues/177).

This's also me.

**Comment by kaikai1024** [comment]
Later. 
new solution, check #283
