### ISSUE TITLE
Quality: We need version control for function points

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#244]
##### Why we need it

Now, we use a group of online spreadsheets to record incremental (add or delete) function points.

It is difficult to get all function points for a specific version (read all spreadsheets to summary those function points manually? a bit stupid!).

##### Solution

Just add files like ChangeLog, or associate a new git repository?

Keep two kinds function points for any commit:
+ The function points for all versions after current commit (can be removed in any future commits).
+ The function points for compatibility to the previous version (remove these points when we release a new version).

**Comment by kaikai1024** [comment]
I'd like to do this, and we need a plan
