### ISSUE TITLE
Node(network module) can't connect each other when using K8S ### 使用K8S部署CITA 不出块，排查是network节点不能成功互通

### ISSUE THREAD

**Issue by jiangxianliang007** [cryptape/cita#250]
0.17 和 0.18 版本正常，0.19、0.20、0.21 都是相同的现象。

使用 K8S 部署4个 节点 的CITA，节点间是通过域名+端口连接，在启动第一个POD时，其余POD还没启动，network 解析域名失败，现象是node0 连接所有节点失败，node1连接node0成功，连接node2、3失败， node2连接 node0、1成功，连接node3失败，node3连接所有节点成功，需要等所有POD启动后再手动restart cita 才能正常与其他节点连接，请问这里该怎么解决。

![image](https://user-images.githubusercontent.com/24754263/53087985-6f6ce800-3543-11e9-895e-9c55eeb24b5c.png)

**Comment by ouwenkg** [comment]
这是在 p2p 合并到 cita 的版本上吗？

**Comment by kaikai1024** [comment]
什么版本？

**Comment by jiangxianliang007** [comment]
0.17 和 0.18 版本正常，0.19、0.20、0.21 都是相同的现象。

**Comment by kaikai1024** [comment]
@leeyr338

**Comment by leeyr338** [comment]
能把0.21版本的完整错误调用栈附上吗？

**Comment by jiangxianliang007** [comment]
![image](https://user-images.githubusercontent.com/24754263/53147065-5e72b400-35e1-11e9-838a-d5b6fd7d4318.png)
![image](https://user-images.githubusercontent.com/24754263/53147104-7d714600-35e1-11e9-86be-a48be3a35aa8.png)
![image](https://user-images.githubusercontent.com/24754263/53147146-9974e780-35e1-11e9-805d-a61bf4448b9e.png)
![image](https://user-images.githubusercontent.com/24754263/53147180-b5788900-35e1-11e9-938a-406a2721097d.png)
这是每个节点的 network log

**Comment by leeyr338** [comment]
**根因分析**
1. network模块的配置文件network.toml中配置的peer ip为域名；
2. 在K8S系统中，如果POD没有启动，peer的域名解析不出具体的ip，出现上文的"Can't convert to socket address , ..."的error.
3. **network模块中仅在启动时，进行一次域名到ip的解析**。当本节点先于peer节点启动，将会导致peer无法被解析，然后peer被丢弃。
4. 最终导致区块链网络无法组网。

**解决方案**
当出现peer域名解析出错时，需要延后再尝试解析。

**计划版本时间**
v0.22

**Comment by kaikai1024** [comment]
> **根因分析**
> 
> 1. network模块的配置文件network.toml中配置的peer ip为域名；
> 2. 在K8S系统中，如果POD没有启动，peer的域名解析不出具体的ip，出现上文的"Can't convert to socket address , ..."的error.
> 3. **network模块中仅在启动时，进行一次域名到ip的解析**。当本节点先于peer节点启动，将会导致peer无法被解析，然后peer被丢弃。
> 4. 最终导致区块链网络无法组网。
> 
> **解决方案**
> 当出现peer域名解析出错时，需要延后再尝试解析。
> 
> **计划版本时间**
> v0.22

Are you still working on this?

**Comment by kaikai1024** [comment]
#211
