### ISSUE TITLE
摘要：【CITAHub Docs-自动执行】关于自动执行的文档描述中，在初始化链的时候没有说明要加上--contract_arguments SysConfig.autoExec=true参数。

### ISSUE THREAD

**Issue by wangfh666** [cryptape/cita#252]
摘要：【CITAHub Docs-自动执行】关于自动执行的文档描述中，在初始化链的时候没有说明要加上--contract_arguments SysConfig.autoExec=true参数。

前提条件：

操作步骤：
1、打开链接https://docs.citahub.com/zh-CN/cita/system/auto-exec，进入自动执行文档说明页面；
2、查看文档描述 --KO；

预期结果：关于自动执行初始化链时应该加上--contract_arguments SysConfig.autoExec=true参数，文档中应该添加相应的说明。

实际结果：文档中并未说明自动执行在初始化链时需要添加参数--contract_arguments SysConfig.autoExec=true，快速入门中也未做说明。

**Comment by wangfh666** [comment]
关于自动执行的文档描述中初始化链的描述需要加一下，目前的文档描述关于初始化链这块不是很明确的，在0.21版本的测试中测试这边基本都遇到这个问题，以为在初始化链时，起一条普通链就可以，然后在测试的过程中发现出现问题，以为是程序出现了BUG，在和鹏飞的再三确认后才知道在初始化链时需要加上--contract_arguments SysConfig.autoExec=true参数。

**Comment by ouwenkg** [comment]
#225 The same as this issue

**Comment by kaikai1024** [comment]
I will transfer it to the cita-hub doc later.
