### ISSUE TITLE
Replace tx_tool

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#254]
## Description

Use Rust SDK ~~or Python SDK~~.

## Additional Information

------------Chinese-----------

tx_tool 现在只有 CI 在使用，替换其他工具~~或者一个更好的 Python SDK~~

**Comment by yangby-cryptape** [comment]
Why do not use rust, directly?
We have a simple [Rust SDK], already.

[Rust SDK]: https://github.com/cryptape/cita-common/tree/8e33f0030a301d2ee1715986f1807fa9293c5015/cita-web3

**Comment by kaikai1024** [comment]
> Why do not use rust, directly?
> We have a simple [Rust SDK](https://github.com/cryptape/cita-common/tree/8e33f0030a301d2ee1715986f1807fa9293c5015/cita-web3), already.

That's one solution. Replace it with Rust SDK. Then we need to rewirte the scripts.
The situation is that many tests of our ci are wireten by Python.

**Comment by ouwenkg** [comment]
Could we some take time to discuss solution for this issue? I would like to have a try.

**Comment by kaikai1024** [comment]
Cool. 
* Rewrite the ci scripts using Rust SDK
* Write a new Python SDK
 
What do you think?

**Comment by ouwenkg** [comment]
Something to be considered：
1. create_cita_config
2. integrate tests in ci

Using Rust SDK:
We have to rewrite create_cita_config.py, this task is already in another issue.

Using Python SDK:
This way may be simple, just take tx tool out and do refactoring work as python sdk.  

I prefer to use Rust SDK and recommend not to put it inside cita-common.

**Comment by kaikai1024** [comment]
> We have to rewrite create_cita_config.py, this task is already in another issue.

CI scripts, not create_cita_config.

I prefer the Rust SDK, too. But i'm a little worried about ci test.
