### ISSUE TITLE
Upgrade Rust Toolchain: `jemalloc` or the system allocator

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#256]
According to the official rust blog: [`jemalloc` is removed by default] since `rust v1.32.0`.

The `rust v1.33.0` is coming. The `rust v1.33.0` release pr was created few minutes ago.

So, any plan to upgrade the rust toolchain? And, `jemalloc` or the system allocator?

[`jemalloc` is removed by default]: https://blog.rust-lang.org/2019/01/17/Rust-1.32.0.html#jemalloc-is-removed-by-default

**Comment by kaikai1024** [comment]
yeah. Will upgrade the toolchain to the latest stable version at v1.0.

I'm not sure about `jemalloc` or the system allocator.

**Comment by yangby-cryptape** [comment]
[Rust 1.33.0] has been released.

[Rust 1.33.0]: https://blog.rust-lang.org/2019/02/28/Rust-1.33.0.html

**Comment by kaikai1024** [comment]
image: ubuntu-18.04-20190304

**Comment by kaikai1024** [comment]
I'd like to continue to use the jemalloc. @yangby-cryptape

**Comment by kaikai1024** [comment]
https://github.com/rust-lang/rust/issues/36963#issuecomment-252029017

**Comment by kaikai1024** [comment]
> I'd like to continue to use the jemalloc

TBD. Will decide it after check the performance

**Comment by kaikai1024** [comment]
tps: 4410 -> 4338
That's acceptable.  use system allocator.
jemalloc still is a choice.
