### ISSUE TITLE
Upgrade Supported Solidity Version

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#262]
Two weeks ago, [Solidity v0.5.4] is released.
But the max version of solidity that CITA support is v0.4.24.
https://github.com/cryptape/cita/blob/34fe9a13eb1c17766677cbfa24103a3ca7056106/scripts/contracts/src/system/SysConfig.sol#L1

So, any plan to upgrade the solidity?

[Solidity v0.5.4]: https://github.com/ethereum/solidity/releases/tag/v0.5.4

**Comment by kaikai1024** [comment]
We'll take this operation very carefully.
I'm not sure before a reseach about evm and solidity.

**Comment by ouwenkg** [comment]
https://blog.ethereum.org/2019/02/22/ethereum-constantinople-st-petersburg-upgrade-announcement/

`CREATE2` and `EXITCODEHASH` instructions may bring potential problems, just a **primary** piece.  

In-depth research is necessary.

**Comment by kaikai1024** [comment]
https://solidity.readthedocs.io/en/v0.5.7/050-breaking-changes.html
