### ISSUE TITLE
The authorities of chain configuration. ## 链级配置：--authorities 将共识节点的地址写到链上，未成功。

### ISSUE THREAD

**Issue by mingxiaowu** [cryptape/cita#263]
## Description

链级配置：--authorities 将共识节点的地址写到链上，未成功。

## Steps to Reproduce

1. 起链：
```
./env.sh ./scripts/create_cita_config.py create  --chain_name test-chain --jsonrpc_port 1337 --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"  --authorities "0xd3c09ab0d4392efbebbec5347621ba10f508d360,0x6d699043dada58181cbbe92a12143cb6cda287bf,0xf4b1ffc44834c09145460ffe9fa90b606b7869ea,0x9b3689ddf70660ffb33b033175846ac1e8f29b3a"  --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"
```
2. 启全部节点
3. 启动失败，bft报错：
```
position:
Thread main panicked at Error while loading PrivateKey: [No such file or directory (os error 2)], cita-bft/src/core/params.rs:48
```

**Expected behavior**: [What you expect to happen]

![issue](https://user-images.githubusercontent.com/8768261/53409931-4c3bb000-39fd-11e9-81b6-4c38f1668ba7.jpg)

**Actual behavior**: [What actually happens]

**Reproduce how often**: [What percentage of the time does it reproduce?]

## Versions

v0.21

**Comment by kaikai1024** [comment]
Please update the version info.
develop?

**Comment by jerry-yu** [comment]
PrivateKey  file lost ?

**Comment by kaikai1024** [comment]
`authorities` should be the private key. 
check the [chain config](https://docs.citahub.com/en-US/cita/configuration/chain-configuration#authorities-%E5%B0%86%E5%85%B1%E8%AF%86%E8%8A%82%E7%82%B9%E7%9A%84%E5%9C%B0%E5%9D%80%E5%86%99%E5%88%B0%E9%93%BE%E4%B8%8A) doc.

**Comment by kaikai1024** [comment]
> PrivateKey file lost ?

第一步起节点之后没有 `test-chain/0/privkey` 文件？

**Comment by mingxiaowu** [comment]
启动之后，没有 privkey这个文件

**Comment by jerry-yu** [comment]
需要有的啊，bft 需要知道私钥来进行签名的。create 脚本被谁修改了吗？

**Comment by kaikai1024** [comment]
我先尝试复现

**Comment by leeyr338** [comment]
`privkey` lost when using option `--authorities`.

**Comment by leeyr338** [comment]
如 [文档](https://docs.citahub.com/zh-CN/next/cita/configuration/chain-config) 的描述：

> **--authorities 将共识节点的地址写到链上**
> 安全起见，我们建议的流程是：先由每个共识节点单独生成各自的私钥和地址，私钥请务必由自己妥善保管；地址交由负责起链的管理员，通过该命令写到链上。起链后，生成的 test-chain/*/privkey 文件为空，由各节点独自将自己的私钥填写进来。
> 没有传递参数的话，默认会自动生成对应节点数量的私钥/地址对：地址写到链上；私钥存放在各个节点的 test-chain/*/privkey 文件里。

这里有两个问题：

1. `cita create` 需要生成一个空的 `privkey` 的文件，但没有生成；这是 CITA 的 bug, 需要 fix。
2. 如果指定了 `authorities` , 需要用户主动填写 `privkey` 文件；这是操作上的问题，需要更正。
