### ISSUE TITLE
An independent image for creating cita config.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#270]
## Description

Split the old cita_run image to a new cita_run image and another image fo creating config. 

## Versions

develop

## Additional Information

------------Chinese---------

原因有两个：
* 现在 创建配置 和 运行 其实是独立的两个过程，两个依赖的环境也比较独立。但是现在用的是同一个 `cita_run`，可以考虑把 创建配置 依赖的 python 环境单独一个 image
* #243 需要在启动镜像的时候把指定的任意路径的文件挂载，现在只是挂载 `target/install` ，而脚本有判断是否 容器在运行，或者改 env.sh 脚本不进行判断，每次重开镜像（下策）

**Comment by kaikai1024** [comment]
@ouwenkg Check this.

**Comment by kaikai1024** [comment]
cita run: ubuntu-18.04-20190228
cita create config: config-ubuntu-18.04-20190228

@ouwenkg Need to fix the env.sh script and check the #243 and #242

**Comment by ouwenkg** [comment]
Cool

**Comment by ouwenkg** [comment]
I think  address, privkey, genesis.json is no need to move.

**Comment by kaikai1024** [comment]
> I think address, privkey, genesis.json file in node directory is no need to move.

yeah, just the configs
