### ISSUE TITLE
[Bug] Build fail on CentOS

### ISSUE THREAD

**Issue by leeyr338** [cryptape/cita#272]
## Description
Build fail on CentOS

## Steps to Reproduce
1. Enter root
2. Following the step in https://docs.citahub.com/en-US/cita/getting-started.
3. While running `./env.sh make release`

Error reported:
![wechatimg108](https://user-images.githubusercontent.com/38514341/53556784-8a60dd00-3b7f-11e9-97c8-722b055f9869.png)

**Expected behavior**: [What you expect to happen]
Build ok.

**Actual behavior**: [What actually happens]
Build fail,

**Reproduce how often**: [What percentage of the time does it reproduce?]
Always

## Versions

[The versions of the CITA, operating systems or VM software you use]
v0.21
CentOS @  VMWare

## Additional Information
1. Using root to run `./env.sh`, it shows enter docker as `user`, but we expected as `root`.

**Comment by kaikai1024** [comment]
Nice description!

**Comment by leeyr338** [comment]
I am trying this task in CentOS, but it works well. 
So I think this a very special situation for CentOS@ VMWare.

We can put it into a lower priority to solve. If someone else encounters the same problem, we can analyze it in depth.

**Comment by kaikai1024** [comment]
ok.
Please close it and use the `question` label.
