### ISSUE TITLE
Sync can store non continuous block

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#274]
##### Description & Reproduce

I change the database which store the block bodies, and **add a `panic` if the new block which will be inserted is not continuous in database API**.

- https://github.com/cryptape/cita/blob/dd3e0cea53b9f96c3bcd9d387d5eead7042646d1/cita-chain/core/src/libchain/chain.rs#L1390-L1396
- https://github.com/cryptape/cita/blob/dd3e0cea53b9f96c3bcd9d387d5eead7042646d1/cita-chain/core/src/libchain/chain.rs#L571-L577

The chain always panics with a warning message when sync from other nodes.

> 2019-02-28T11:18:01.118191187+00:00 - INFO - Session initialized
> 2019-02-28T11:18:02.031926652+00:00 - INFO - chain config: Config { prooftype: 2, cache_size: > Some(1048576) }
> 2019-02-28T11:18:02.033004280+00:00 - INFO - get chain max_store_height : 20  current_height: 19
> 2019-02-28T11:18:13.072729295+00:00 - WARN - sync: insert block-19 is not continious proof height 18

##### Unexpected Behavior
- The first sync block always is the last block the chain already has.
- The chain can save non continuous block from sync.

**Comment by kaikai1024** [comment]
I'm trying to reproduce, only once...
keep trying

**Comment by ouwenkg** [comment]
Now, i can not reproduce the situation of sync blocks out of order. Futher discussion later.
