### ISSUE TITLE
Chain receive sync message for height 20~39, again and again

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#276]
##### Description

Chain receive sync message for height 20~39, again and again.

This is a probabilistic unexpected event.
This event doesn't cause any fatal errors, now.

##### Reproduce

- I run a chain with 3 node.
- Send transactions to node 1 and node 2, continuously. (Why not node 3? because I want to check trace logs of node 3)
- Read logs of node 3, I find that chain receive sync message for height 20~39, again and again.
- Stop sending transactions to node 1 and node 2.
- Chain still receive sync message for height 20~39, again and again.
- The chain isn't abnormal.

##### Logs

These messages are print in log, again and again:
> sync: receive sync from node 3, height lists = [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
> sync: reply node = 3, response blocks len = 20

##### Notice

This node is the node 3, it sends sync request to itself and reply to itself.

**Comment by kaikai1024** [comment]
That's wierd...

**Comment by yangby-cryptape** [comment]
I modify some code, so I'm not so sure if it's a common event.
I just record this, when I finished my feature, I will try to check it, again.

**Comment by ouwenkg** [comment]
![选区_039](https://user-images.githubusercontent.com/11801722/56644302-03773f00-66ae-11e9-9b29-a0af1daf3ada.png)

在复现问题的时候，发现一个不太懂的事情，这里的 node id 怎么就是 7  了,我就起了四个节点.

**Comment by ouwenkg** [comment]
> These messages are print in log, again and again:
> 
> > sync: receive sync from node 3, height lists = [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
> > sync: reply node = 3, response blocks len = 20

这些日志应该不是节点 3 打印出来的吧. 代码里是在 https://github.com/cryptape/cita/blob/develop/cita-chain/src/forward.rs#L415-L418, 这里处理其他节点同步块的请求. 这个 node id 有毒,不可信.为什么有毒,还要排查一下

**Comment by kaikai1024** [comment]
> 这里的 node id 怎么就是 7 了,

是 develop 吗？ @leeyr338 这里 id 是什么？

**Comment by ouwenkg** [comment]
是最新的版本.过程: 四节点的链, 先跑三个节点 0, 1, 2, 然后拼命往节点 0, 1 发交易,随后启动节点 3 . 在节点0 下 cita-chain.log 就会发出这样的log

**Comment by leeyr338** [comment]
这个 `origin` 其实不是 `node` 的概念了。在 p2p 里，它指的是 session_id, 这个 id 是 p2p 分配的。

**Comment by leeyr338** [comment]
你可以在 `cita-network.log` 中找到这个 `id` 对应的 node.

**Comment by ouwenkg** [comment]
```
1774 2019-04-24T16:24:31.355141465+08:00 - DEBUG - sync: reply node = 3, response blocks len = 20
```
reply node = 3, 这个 3 来自于 origin 字段,是 network 模块分配的一个 session id. 在 issue 里恰好等于3, 误以为是节点 3 自己同步自己了.
