### ISSUE TITLE
A new RPC interface to return all the ip and node addresses. 

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#280]
## Description

* [x] A `peersInfo` interface
* [ ] ~~(optional)Make this feature configurable~~

## Versions

develop

## Additional Information

----------Chinese----------
RPC服务提供 `peersInfo` 接口，返回所有节点的 ip 和 node addres

**Comment by leeyr338** [comment]
## peersInfo

Get all peers information. 
- A peer is a node which connected to queried node. For example, if A connected to B, C, D, while we get `peersInfo` from A, that the peers will be B, C and D.
- peers information will contains `peer address` and `peer ip`.

### Parameters

None

### Returns

Object - peers informaction

### Example
- Request
```json
curl -X POST --data '{"jsonrpc":"2.0","method":"peersInfo","params":[],"id":74}'
```

- Result
```json
{
    "id": 74,
    "jsonrpc": "2.0",
    "result":  {
        amount: "0x3",
        info: {
            "0x2b027dacd33a41ddb09e21805778f19951776ed5": "12.123.14.53",
            "0x2b027dacd33a41ddb09e21805778f19951776ed6": "32.52.64.32",
            "0x2b027dacd33a41ddb09e21805778f19951776ed7": "67.68.32.21",
        },
    },
}
```

**Comment by leeyr338** [comment]
For security reasons, It is better to make this feature configurable. Use
```
enable-peerInfo = 0
```
in `jsonrpc.toml` to enable this RPC interface or not (0: disable, 1: enable).
Set `enable` as default. 
When `disable`, user will get some information like:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32601,
    "message": "Disabled interface"
  }
}
```

**Comment by kaikai1024** [comment]
refer https://github.com/cryptape/cita/issues/282
