### ISSUE TITLE
Config the log module

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#281]
## Description

Can specify the way to output logs. (file of stdout)

## Versions

develop

## Additional Information

-----------Chinese--------

CITA的日志模块要可以配置输出方式，以对容器云更加友好。（如可配置成日志文件输出或控制台输出

**Comment by Kayryu** [comment]
实现思路：
* 通过传参（--stdout -s）控制日志输出，默认输出到文件。
* 输出到控制台时，为区分不同模块，会在原有日志基础上增加模块信息，对输出到文件不做改动。
* 如要统一管理，可以在forever.toml文件中增加启动参数，本次不对该文件改动。

本次改动涉及： cita-common/log, cita-* 模块

**Comment by kaikai1024** [comment]
cool
