### ISSUE TITLE
Get release version info of all modules from RPC.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#282]
## Description

Get release version info of all modules from RPC.

## Versions

develop

## Additional Information

------------Chinese--------
需要接口返回软件版本号信息

**Comment by Kayryu** [comment]
实现思路：
* 通过新增RPC 接口 `getVersion()`获取软件版本号信息， 现cita微服务架构理论上需要返回所有模块的版本号信息，考虑到最小改动，用JsonRPC模块版本代表整体版本号。
* RPC请求返回格式 
```
{
"jsonrpc": "2.0",
    "id": 2,
    "result": {
        "softwareVersion": "0.20"
    }
}
```
*  用户通过参数控制该接口能否获取到正确信息，`--hide  -h`表示隐藏自己的软件版本，这时接口返回 ` "softwareVersion": ""`。默认是可以获取到软件版本号。

本次改动涉及模块: cita-common/jsonrpc-types, cita-jsonrpc

**Comment by kaikai1024** [comment]
我觉得默认不返回比较好吧，因为加这个控制是因为安全问题，用户一般都不会特别设置，有特别要显示需求的会接受设置一下

**Comment by Kayryu** [comment]
> 我觉得默认不返回比较好吧，因为加这个控制是因为安全问题，用户一般都不会特别设置，有特别要显示需求的会接受设置一下

如果默认不返回，会迷惑SDK使用者，都不知道这个接口是干啥的，索性就不暴露它了。我觉得既然加了这个接口默认就是有正确返回的。

**Comment by leeyr338** [comment]
其实这里有两种思路：
1. 需要在RPC接口描述上加以说明；告用户当返回""时，表示节点软件没有开启版本访问功能。
2. 在这个RPC接口中添加一个Error域，当没有开启版本访问功能时，返回给用户一个明确的信息。

我个人比较倾向于第2种。

**Comment by rainchen** [comment]
可以这样：
1. 使用启动参数，例如 --enable_version
2. RPC 服务 getVersion 接口可以返回

1. 使用不增加启动参数
2. 不开启，RPC 服务 getVersion 接口，访问时是404（接口不存在）

不知道在现有架构实现难不难？

**Comment by leeyr338** [comment]
Can this issue be closed?

**Comment by kaikai1024** [comment]
#359 https://github.com/cryptape/citahub-docs/issues/104

**Comment by kaikai1024** [comment]
> Can this issue be closed?

done
