### ISSUE TITLE
Docker improvement advices

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#308]
## Description

This issue for all advices about improving docker usage

While working on issue #212 , i plan to add py-checker tool in cita image. 

Meanwhile, I want to collect more greatful suggestions about our cita-run image.

Those tools you think should be in our image, but not include now, like vim supporting. please let me know.
Or which tools in our image you think is junk and should be deleted, please me know too.

We will consider your opinion and puting it together, then add it to our new image. 

@cryptape/citaman @keroro520 @driftluo @yangby-cryptape @u2

**Comment by keroro520** [comment]
sysstat, vi

**Comment by kaikai1024** [comment]
According to the current situation，The only job of cita_run image is to run the cita.
I don't think it's a good idea to put other tools in the image.
Does the tool(like vim) is must-have to run cita?

#202 is another question, stil, i think the image should be small and simple

**Comment by keroro520** [comment]
I agree that keeps docker-image tiny. "sysstat, vi" is not must-have.

**Comment by yangby-cryptape** [comment]
### No tools for development or devops

For example, if we provide `vi` / `vim`, maybe some guys will complain:
> `vi`? Why do not provide `nano`!
> There is a `vim`? D**n it, I am a emacser!

### (Further) Docker should **NOT** be our first choice to publish the binaries

I read a lot manuals of server application. Most of them provide a detailed document as  the first choice to show how to run the server step by step. Docker just is optional.

Ubuntu, and maybe only _Bionic Beaver_? Docker? K8s? **Nobody like software family buckets!**

Suppose I was a normal user, I really want to say: just give me a bootstrap for setup a minimum available environment!

**Comment by ouwenkg** [comment]
We use **RUST**, that so cool, But our usage is so unfriendly.

I am not clear enough to know about why we use docker in the last long time. 

Compiling problem in mac os is one of the biggest problems i know about this. What if we solve this problem and add step-by-step docs in different os environments. Can we dicard docker usage?

In my mind, the perfect situation must be `cd cita`, then,  `cargo build` that all.

**Comment by yangby-cryptape** [comment]
> Compiling problem in mac os is one of the biggest problems i know about this.

As a server software, maybe we should consider that let cita supports the top 3 most popular linux server distribution at first.
