### ISSUE TITLE
cita 0.20's upgrade not compatible of 0.19

### ISSUE THREAD

**Issue by jerry-yu** [cryptape/cita#311]
cita 0.19's global config has one param delay_num which makes the change of config delay N blocks to be effective.  But 0.19's delay num default is 2,and 0.20+'s delay num default is 1.

So , block sync from begining will be  blocked due to the version upgrade

**Comment by kaikai1024** [comment]
@yangby-cryptape @u2 Any idea?

**Comment by kaikai1024** [comment]
* Copy the data
* Use snapshot
