### ISSUE TITLE
cita-executor seems occur memory leak ## cita-executor 疑似 内存泄漏

### ISSUE THREAD

**Issue by jiangxianliang007** [cryptape/cita#316]
我在一台64G内存的机器上 压测 CITA、cita-executor的内存占用很高、3个进程在10%和20%，一个进程在4%，我重启了一个节点后那个节点就下降了。
4个节点大概占用60% 差不多40G内存。

![image](https://user-images.githubusercontent.com/24754263/54268355-f7c83100-45b5-11e9-9a71-e2612d0a7815.png)

内存高的版本 CITA JsonRpc v0.21rc-51-g6119c3f
Ubuntu 16.04.3

JsonRpc v0.20rc-325-gfb82527 版本没有这个情况。

**Comment by kaikai1024** [comment]
谢谢！
我们会尽快看一下

**Comment by kaikai1024** [comment]
#588
