### ISSUE TITLE
Add pylint checker in ci

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#317]
# Pylint checker

## Description

Most of py code in ci used for tests. 

But, there are some key scripts such as `create_cita_config.py`, `create_genesis.py`, `create_init_data.py`, we could use pylint to bring these scripts more robustness.

**Comment by kaikai1024** [comment]
:smile: You are not a newcomers.

**Comment by kaikai1024** [comment]
We will consider to rewrite the Python code. #233 

So do not need to add pylint into ci.
Maybe we'll refuse Python code in the future.
