### ISSUE TITLE
How about adding a Homebrew formula?

### ISSUE THREAD

**Issue by clearloop** [cryptape/cita#331]
# How about adding a Homebrew formula? 
> I had configured CITA last night, the starting instructors might too long that made me confused, btw, I wrote a formula and made few changes in my branch. 

# [Solution][2] 

__It's quite nice to replace the `$PWD` as `$CITA_HOME`, homebrew might not happy about `$PWD`...__

## Installation
> Install [Docker Server][1] first.

__To use docker happily, we need:__
+ Click docker icon
+ share `/usr/local/Cellar/cita`

__Tap repo and install:__

```
brew tap clearloop/cita
brew install cita
```

__By default, binaries installed by cita will be placed into:__

```
/usr/local/Cellar/cita/0.21
```

## Usage

Just exec `cita`:

```
Usage: cita <command> <node> [options]
where <command> is one of the following:
    { help | setup | start | stop | restart | ping
      top | backup | clean | logs | logrotate }

Run `cita help` for more detailed information.
```

### preset
```
# This version has a preset test-chain, no need to run scripts.
```

### Setup Chain
```
$ cita setup test-chain/0
```

### Start Chain
```
$ cita start test-chain/0
```

### Stop Chain
```
$ cita stop test-chain/0
```

### Others
```
$ cita
Usage: cita <command> <node> [options]
where <command> is one of the following:
    { help | setup | start | stop | restart | ping
      top | backup | clean | logs | logrotate }
Run `cita help` for more detailed information.
```

# Additions
Complex operations might block some developers interested in, hope cita team can simplify the installation and operating process ; )

[1]: https://www.docker.com/get-started
[2]: https://github.com/clearloop/cita/releases/tag/cita%400.21

**Comment by kaikai1024** [comment]
Awesome!  :+1: 

We will check the code asap. btw, you can new a pr, and welcome to contribute the code. :heart: 

> Complex operations might block some developers interested in, hope cita team can simplify the installation and operating process

yeah, we will take it very seriously. and we already have some issues about this,  #202 #308 #310 , still work on it. look forward to your attention and advice

> I had configured CITA last night, the starting instructors might too long that made me confused

Some advice about this? You can point out any part that you feel confused, Contribute a pr if you would like.

Thank you very much.

**Comment by leeyr338** [comment]
Yes, as what you are talking in your PR #334 , It is great idea to support running CITA with docker. So let's start with `MacOS`?

Btw,  if cryptape fork your repo `clearloop/hypercask`, is it possible to tap repo and install like:
```
brew tap cryptape/hypercask
brew install cita
```
?

**Comment by clearloop** [comment]
> Btw, if cryptape fork your repo `clearloop/hypercask`, is it possible to tap repo and install like:

Never mind, the formula is really easy, just take my code, it's only rock n' roll.

If CITA teem prefer to, I have just created a new GPLv3 [repo][1] with clean history but one commit as cita formula, I can transfer the repo to cryptape, ever `homebrew-hypercask` or `homebrew-cita`, it's all cool, btw, hypercask is an awesome name...LOL

btw, the amazon file server is really slow, it's nice to replace the compressed code in a faster place.

[1]:https://github.com/clearloop/homebrew-cita

**Comment by leeyr338** [comment]
Can it be a MIT license? We are have a plan to move all GPLv3 code into MIT https://github.com/cryptape/cita/issues/253 https://github.com/cryptape/cita/issues/348 . So it's better to be a MIT license.

**Comment by clearloop** [comment]
It's okay, I've changed it just now, should I transfer it to cryptape now? Then CITA team can modify the formula soon as possible.

**Comment by kaikai1024** [comment]
Thank you. I will check your repo later.

**Comment by clearloop** [comment]
> Thank you. I will check your repo later.

Well, I find that I can't transfer XD, just take the code, no need fork if it is not necessary.

**Comment by kaikai1024** [comment]
>  just take the code, no need fork if it is not necessary.

That's not the way we work. 

We will accept the contributions(pull request) or we will fork your repo.

**Comment by clearloop** [comment]
> We will accept the contributions(pull request) or we will fork your repo.

That sounds nice, I prefer to make a pr but not being forked.

**Comment by kaikai1024** [comment]
I will follow the discussions.

btw, What's the progress of this pull request? @leeyr338

**Comment by kaikai1024** [comment]
@clearloop 
I's confused about the [url](https://github.com/clearloop/homebrew-cita/blob/master/cita.rb#L7)
Why not use our official bin? and why ed25519?

**Comment by clearloop** [comment]
> Why not use our official bin? and why ed25519?

__bin file:__
The official bin's path in `env.sh` and `cita` is based on `pwd`, that the command will come to chaos while we install `cita` global, it is the directly reason that I made the pr #334, replacing `pwd` as `$1`.

__ed25519:__
About the `ed25519`, I just chose the first file of [cita-v0.21 releases][1]...btw, `ed25519` is popular these years, more and more projects switch Ed25519 from ECDSA~ 

As the same reason before, too many choices block users, they don't know how to choose, it's friendly to:

```
brew install cita
# and more choices:
brew install cita@ed25519
brew install cita@secp256k1
...
```

[1]: https://github.com/cryptape/cita/releases/tag/v0.21

**Comment by kaikai1024** [comment]
Got it.

> too many choices block users, they don't know how to choose

yeah, that's what we need to do.

**Comment by kaikai1024** [comment]
Would you like to pull a request about this?

**Comment by clearloop** [comment]
Yep, and I'd like to use official compiled code.

**Comment by kaikai1024** [comment]
cool.
You can add the `cita.rb` to this repo(maybe another name).
And `README` to the citahub-docs

btw, the latest release version: https://github.com/cryptape/cita/releases/tag/v0.22.0

**Comment by kaikai1024** [comment]
https://github.com/cryptape/homebrew-cita
