### ISSUE TITLE
The plan of removing GPL.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#348]
## Description

TBD

* [ ] [evm](https://github.com/cryptape/cita/tree/develop/cita-executor/evm)
* [ ] [chain/types](https://github.com/cryptape/cita/blob/develop/cita-chain/types/README.md)
* [ ] [chain/core](https://github.com/cryptape/cita/blob/develop/cita-chain/core/README.md)
* [ ] [executor/core](https://github.com/cryptape/cita/blob/develop/cita-executor/core/README.md)

## Additional Information

#253

**Comment by kaikai1024** [comment]
https://github.com/cryptape/rust-numext

**Comment by leeyr338** [comment]
And some dependents:
[] parity-snappy-sys
[] libsm
[] ethcore-bloom-journal

**Comment by jerry-yu** [comment]
done
