### ISSUE TITLE
The problem of CircleCI

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#349]
## Description

someone can't trigger the build of CircleCI

## Additional Information

#336 https://github.com/cryptape/cita-common/pull/228 https://github.com/cryptape/cita-common/pull/236

**Comment by kaikai1024** [comment]
@zhouyun-zoe Any progress?

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita-common/pull/247

I can not use it either.

**Comment by kaikai1024** [comment]
Could it be solved before the holiday? @zhouyun-zoe 

https://github.com/cryptape/cita/pull/387
and i still can not use CI of cita-common.

Please give me some info about the progress. 
and i will consider to change the CI.

**Comment by kaikai1024** [comment]
If you have no time to deal this. Please let me know

**Comment by zhouyun-zoe** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/36949326/55388327-a6ccac80-5565-11e9-9129-6bb2280be054.png">

**Comment by zhouyun-zoe** [comment]
I sent an email to ask for Zoom meeting one more(they just ignore my requirement in the last email). 
Their work is really inefficient so it's really hard to get contact with their support every day.
I'll keep this ticket and I'm thinking if you can open another ticket for the same problem.

**Comment by kaikai1024** [comment]
I've already to ask for a new ticket.

And i'll try to use AppVeyor

**Comment by zhouyun-zoe** [comment]
Problem solved.

Currently, when the forked project connects to CircleCI, the main project can't trigger a build by a pull request even the main project is turning on `build forked pull request` option.

So,  if your commit cannot trigger the build of CI, check if this commit was triggered by the forked repo build. Click into your own CI setting(such as:https://circleci.com/gh/kaikai1024/cita-common/edit), unfollow the repo and the problem can be solved.
