### ISSUE TITLE
Remove the quotaPrice must greater than zero limitation

### ISSUE THREAD

**Issue by CipherWang** [cryptape/cita#350]
# QuotaPrice couldn't be set to zero

## Description
In some scenarios, operators want to keep transaction fee zero in charge mode. However, current quotaPrice setup only accept a non-zero value. Could we remove this limitation ?

**Comment by kaikai1024** [comment]
The code (limitation) is here: https://github.com/cryptape/cita/blob/develop/scripts/contracts/src/system/PriceManager.sol#L35

The situation is:

quotaPrice can be setted to zero when start a chain, as you said, only accept a non-zero value when CITA is running. 

Remove this limitation has a compatibility risk:

If a v0.21 version chain has a transaction that setting the quotaPrice to zero, and the receipt is `revert`, the new version chain will get a receipt `success`. 
That's a problem.

**Comment by kaikai1024** [comment]
Not sure about this.
Need more information.

@rink1969 Do you know the situation?

**Comment by ouwenkg** [comment]
Now, the default quota price is 1000000. In the scenarios descripted above, What if we send tx and send quota price only 1.

default price: 1000000
setting price: 1 

Is this work?

**Comment by CipherWang** [comment]
> Now, the default quota price is 1000000. In the scenarios descripted above, What if we send tx and set quota price only 1.
> 
> default price: 1000000
> setting price: 1
> 
> Is this work?

There is a gap between zero and non-zero quota price, users have to hold system tokens to send tx, even the price is 1.

Here is the temporary solution, guide users to set quotaPrice = 0 on genesis, and the superadmin could change it to non-zero later.

**Comment by kaikai1024** [comment]
> Here is the temporary solution, guide users to set quotaPrice = 0 on genesis, and the superadmin could change it to non-zero later.

I have updated the doc about [amending the quotaPrice to 0](https://github.com/cryptape/cita/wiki/Amend-quotaPrice-to-0). 
Admin can follow it after starting the CITA.
