### ISSUE TITLE
rpc getFilterLogs return none

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#352]
# Rpc getFilterLogs return none

## Description

https://docs.citahub.com/en-US/cita/rpc-guide/rpc#getfilterlogs

In my opinion, this method's usage is the same as [getFilterChanges](https://docs.citahub.com/en-US/cita/rpc-guide/rpc#getfilterchanges)
 
But always return none. 

## Steps to Reproduce

#294 shows how to use getFilterChanges and get values.

**Expected behavior**: [What you expect to happen]

Behave like getFilterChanges.

**Actual behavior**: [What actually happens]

Return none

**Reproduce how often**: [What percentage of the time does it reproduce?]

ever

## Additional Information

If these two interfaces `getFilterChanges` and `getFilterLog`  do the same things.

 Why two? Just for compatible with Ethereum.

Another question:
We are quite different from ethereum at the beginning, we are not compatible 
all the time and why add these redundant things to deceive ourself.

**Comment by kaikai1024** [comment]
The first choice is to maintain the interfaces.
Deprecation is a serious decision, need to be disscussed.

**Comment by jerry-yu** [comment]
done
