### ISSUE TITLE
Both nodes run normal when copy from a node without changing address and privkey ## 手动复制一个节点，不修改address和privkey,目前这两个节点都正常出块

### ISSUE THREAD

**Issue by mingxiaowu** [cryptape/cita#354]
## Steps to Reproduce

1. stop节点 0，复制节点 0 为 4，启动节点 0；
2. 节点 4 的：删除 data 和 log；修改 network.toml, executor.toml, jsonrpc.toml, .env；不修改 address 和privkey；
3. 启动节点 4；

**Expected behavior**:
 
节点 4 和节点 0 的 address/privkey 相同，所以节点 4 应该被 kill

## Versions

v0.22.0-rc

**Comment by leeyr338** [comment]
一个区块链网络没有权限去`kill`一个节点，网络能做的仅是**阻止它加入这个网络**。

**Comment by kaikai1024** [comment]
Bft will treat them as a same node, right? @KaoImin

**Comment by KaoImin** [comment]
> Bft will treat them as a same node, right? @KaoImin

Yes

**Comment by leeyr338** [comment]
We have to fix this bug in `network`, make `node 4` cannot access into the block-chain. I am working on this.
