### ISSUE TITLE
The test of getVersion.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#359]
## Description

Add the unit test of getVersion

## Additional Information

#351

**Comment by leeyr338** [comment]
Can anyone help to support this JSON-RPC interface for cita-cli?
https://github.com/cryptape/cita-cli/issues/106

**Comment by kaikai1024** [comment]
Use `curl` to test if if works.

I mean the `unit test` is adding a schema in `/tests/interfaces`.

**Comment by kaikai1024** [comment]
Would you please to check if @Kayryu is doing this? @leeyr338

**Comment by Kayryu** [comment]
sorry! I didn't do it. If not urgent, I will add it

**Comment by kaikai1024** [comment]
> sorry! I didn't do it. If not urgent, I will add it

You can try it if you would like to. I just need to know the progress and decide to do or not.
