### ISSUE TITLE
 Integrate state test

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#366]
## Description

Run [State test](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/) in cita embedded state module.

## Record

* [x] ./tests/jsondata/GeneralStateTests/stRefundTest
* [x] ./tests/jsondata/GeneralStateTests/stCodeCopyTest
* [x] ./tests/jsondata/GeneralStateTests/stMemExpandingEIP150Calls
* [x] ./tests/jsondata/GeneralStateTests/stCallDelegateCodesCallCodeHomestead
* [x] ./tests/jsondata/GeneralStateTests/stRevertTest
* [x] ./tests/jsondata/GeneralStateTests/stArgsZeroOneBalance
* [x] ./tests/jsondata/GeneralStateTests/stMemoryStressTest
* [x] ./tests/jsondata/GeneralStateTests/stTransactionTest
* [x] ./tests/jsondata/GeneralStateTests/stReturnDataTest
* [x] ./tests/jsondata/GeneralStateTests/stPreCompiledContracts
* [x] ./tests/jsondata/GeneralStateTests/stCodeSizeLimit
* [x] ./tests/jsondata/GeneralStateTests/stHomesteadSpecific
* [x] ./tests/jsondata/GeneralStateTests/stEIP158Specific
* [x] ./tests/jsondata/GeneralStateTests/stZeroKnowledge2
* [x] ./tests/jsondata/GeneralStateTests/stCreateTest
* [x] ./tests/jsondata/GeneralStateTests/stSStoreTest
* [x] ./tests/jsondata/GeneralStateTests/stTransitionTest
* [x] ./tests/jsondata/GeneralStateTests/stZeroCallsTest
* [x] ./tests/jsondata/GeneralStateTests/stBadOpcode
* [x] ./tests/jsondata/GeneralStateTests/stLogTests
* [x] ./tests/jsondata/GeneralStateTests/stNonZeroCallsTest
* [x] ./tests/jsondata/GeneralStateTests/stCallDelegateCodesHomestead
* [x] ./tests/jsondata/GeneralStateTests/stBugs
* [x] ./tests/jsondata/GeneralStateTests/stShift
* [x] ./tests/jsondata/GeneralStateTests/stWalletTest
* [x] ./tests/jsondata/GeneralStateTests/stRandom2
* [x] ./tests/jsondata/GeneralStateTests/stEWASMTests
* [x] ./tests/jsondata/GeneralStateTests/stStaticCall
* [x] ./tests/jsondata/GeneralStateTests/stAttackTest
* [x] ./tests/jsondata/GeneralStateTests/stStackTests
* [x] ./tests/jsondata/GeneralStateTests/stPreCompiledContracts2
* [x] ./tests/jsondata/GeneralStateTests/stInitCodeTest
* [x] ./tests/jsondata/GeneralStateTests/stZeroKnowledge
* [x] ./tests/jsondata/GeneralStateTests/stEIP150singleCodeGasPrices
* [x] ./tests/jsondata/GeneralStateTests/stChangedEIP150
* [x] ./tests/jsondata/GeneralStateTests/stExample
* [x] ./tests/jsondata/GeneralStateTests/stSolidityTest
* [x] ./tests/jsondata/GeneralStateTests/stEIP150Specific
* [x] ./tests/jsondata/GeneralStateTests/stQuadraticComplexityTest
* [x] ./tests/jsondata/GeneralStateTests/stSystemOperationsTest
* [x] ./tests/jsondata/GeneralStateTests/stZeroCallsRevert
* [x] ./tests/jsondata/GeneralStateTests/stRecursiveCreate
* [x] ./tests/jsondata/GeneralStateTests/stRandom
* [x] ./tests/jsondata/GeneralStateTests/stDelegatecallTestHomestead
* [x] ./tests/jsondata/GeneralStateTests/stMemoryTest
* [x] ./tests/jsondata/GeneralStateTests/stCreate2
* [x] ./tests/jsondata/GeneralStateTests/stSpecialTest
* [x] ./tests/jsondata/GeneralStateTests/stCallCodes
* [x] ./tests/jsondata/GeneralStateTests/stCallCreateCallCodeTest
* [x] ./tests/jsondata/GeneralStateTests/stExtCodeHash

## Additional Information

#222

**Comment by ouwenkg** [comment]
接着上文，又进了一步。详情如下：
CITA 的 Account 进行 rlp 的时候包括 5 项，ethereum account rlp 包括四项，*没有 abi_hash* ：
```
 pub fn rlp(&self) -> Bytes {
        let mut stream = RlpStream::new_list(5);
        stream.append(&self.nonce);
        stream.append(&self.balance);
        stream.append(&self.storage_root);
        stream.append(&self.code_hash);
        stream.append(&self.abi_hash);
        stream.out()
    }
```
我去掉之后，rlp 结构一致了，account 序列化后和 ethereum 一致：

```
Account { balance: 0, nonce: 0, storage_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, code_hash: 0x0be63ce2cadbb887227039e417efb78df1577c888de3936c4ceef7c7266d2ad0 }

rlp account: [248, 68, 128, 128, 160, 86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 1, 98, 47, 181, 227, 99, 180, 33, 160, 11, 230, 60, 226, 202, 219, 184, 135, 34, 112, 57, 228, 23, 239, 183, 141, 241, 87, 124, 136, 141, 227, 147, 108, 76, 238, 247, 199, 38, 109, 42, 208]

Account { balance: 1000000000000000000, nonce: 0, storage_root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421, code_hash: 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470 }

rlp account: [248, 76, 128, 136, 13, 224, 182, 179, 167, 100, 0, 0, 160, 86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 1, 98, 47, 181, 227, 99, 180, 33, 160, 197, 210, 70, 1, 134, 247, 35, 60, 146, 126, 125, 178, 220, 199, 3, 192, 229, 0, 182, 83, 202, 130, 39, 59, 123, 250, 216, 4, 93, 133, 164, 112
```

但是初始化账户的 root hash 还是不一样。
```
{
            let mut trie = self
                .factories
                .trie
                .get_from_existing(self.db.as_hashdb_mut(), &mut self.root)
                .map_err(|err| *err)?;
            for (address, ref mut a) in accounts.iter_mut().filter(|&(_, ref a)| a.is_dirty()) {
                a.state = AccountState::Committed;
                match a.account {
                    Some(ref mut account) => {
                        debug!("account: {:?}", account);
                        debug!("rlp account: {:?}", account.rlp());
                        trie.insert(address, &account.rlp()).map_err(|err| *err)?;    // 插入到 trie 里的 rlp 保证一致性，但是 state.root() 不一样
                    }
                    None => {
                        trie.remove(address).map_err(|err| *err)?;
                    }
                }
            }
        }
```

怀疑是 cita trie 里有 bug，要深入 trie 里看一下，会耗时一些。

**Comment by kaikai1024** [comment]
> 将 abi 等加入 rlp 导致

abi 是存在一个 特殊地址的 code 里的啊，为什么会和这个有关系？

**Comment by ouwenkg** [comment]
> 为什么 会有 `abi_hash`，这个是什么？

设计的初衷我理解是在链上保存 abi，但是实现里，abi_hash 是在全局 state 里，这个太糟糕了，影响巨大。

**Comment by kaikai1024** [comment]
测试过不去的地方直接建个 新的 issue 讨论决定是修改 cita 还是修改测试用例

@ouwenkg abi_hash 这个另建 issue 讨论吧

**Comment by ouwenkg** [comment]
> 测试过不去的地方直接建个 新的 issue 讨论决定是修改 cita 还是修改测试用例
> 
> @ouwenkg abi_hash 这个另建 issue 讨论吧

完全搞明白原因之后，再建吧

**Comment by kaikai1024** [comment]
> 完全搞明白原因之后，再建吧

和这个没关系，issue 是大家都参与的，就是要讨论的，不是要有结论

**Comment by ouwenkg** [comment]
```
   // test_json_path(r"./tests/jsondata/GeneralStateTests/stArgsZeroOneBalance");          // 无 homestead, 无 Frontier
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stPreCompiledContracts");        // 无 homestead, 无 Frontier
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stSStoreTest");                  // 无 homestead, 无 Frontier
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stZeroKnowledge2");              // 无 homestead, 无 Frontier
    // skip_path(r"./tests/jsondata/GeneralStateTests/stEIP158Specific");                   // 无 homestead, 无 Frontier
    // skip_path(r"./tests/jsondata/GeneralStateTests/stEWASMTests");                       // 这个没有用到
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stEIP150singleCodeGasPrices");   // 150 修改了指令计价，我们没有改待研究
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stChangedEIP150");               // 150 相关，待研究
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stStaticCall");                  // 无 homestead, 无 Frontier
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stEIP150Specific");              // 无 homestead, 无 Frontier
    // skip_path(r"./tests/jsondata/GeneralStateTests/stZeroCallsRevert");                  // 无 homestead, 无 Frontier
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stCreate2");                     // 无 homestead, 无 Frontier
    // test_json_path(r"./tests/jsondata/GeneralStateTests/stCallCreateCallCodeTest");      // 无 homestead, 有Frontier
```
Tests without homestead item, we can fix others test firstly. @kaikai1024
