### ISSUE TITLE
The plan of network module test.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#370]
### 正常测试
**不使用域名测试**

- [x]  T001: 单节点正常节点加入；

> 测试目的：节点可以正常发现并接入网络。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 启动一个新的节点，其中的已知节点配置为节点 0 的 ip : port。
> 
> 测试期望：
> 所有节点的连接数为 4。

- [x] T002: 单节点节点正退出；

> 测试目的：网络可以正确感知节点退出。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 关闭共识节点 3 。
> 
> 测试期望：
> 所有节点的连接数为 2。

- [x] T003: 多节点快速加入；

> 测试目的：CITA 网络可以正确处理节点并行加入。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 连续启动 4 个新节点，其中的已知节点配置为节点 0 的 ip : port。
> 
> 测试期望：
> 所有节点的连接数为 7。
> 

- [x] T004: 多节点快速退出；

> 测试目的：CITA 网络可以正确处理节点并行退出。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 连续启动 4 个新节点，其中的已知节点配置为节点 0 的 ip : port。
> 3. 连续退出 4 个新加入的接点。
> 
> 测试期望：
> 所有节点的连接数为 3。

- [x] T005: 多节点快速加入、退出；

> 测试目的：CITA 网络可以正确处理节点并行退出同时并行加入。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 连续启动 4 个新节点，其中的已知节点配置为节点 0 的 ip : port。
> 3. 在启动节点同时，连续退出已经加入的新节点。
> 
> 测试期望：
> 所有节点的连接数为 3。

- [x] T006: 节点加入时，已知节点未启动；

> 测试目的：CITA 网络可以正确处理节点先于已知节点启动场景
> 
> 测试步骤：
> 1. 启动 3 个共识节点 （其中 node 0 先不启动），正常出块。查询所有节点连接数为 2 。
> 2. 启动新节点，其中的已知节点配置为节点 0 的 ip : port。
> 3. 启动 node 0 。
> 
> 测试期望：
> 所有节点的连接数为 3。

**使用域名**

- [x] T011: 单节点正常节点加入；

> 测试目的：节点可以正常发现并接入网络。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 启动一个新的节点，其中的已知节点配置为节点 0 的 ip : port。
> 
> 测试期望：
> 所有节点的连接数为 4。

- [x] T012: 单节点节点正退出；

> 测试目的：网络可以正确感知节点退出。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 关闭共识节点 3 。
> 
> 测试期望：
> 所有节点的连接数为 2。

- [x] T013: 多节点快速加入；

> 测试目的：CITA 网络可以正确处理节点并行加入。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 连续启动 4 个新节点，其中的已知节点配置为节点 0 的 ip : port。
> 
> 测试期望：
> 所有节点的连接数为 7。

- [x] T014: 多节点快速退出；

> 测试目的：CITA 网络可以正确处理节点并行退出。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 连续启动 4 个新节点，其中的已知节点配置为节点 0 的 ip : port。
> 3. 连续退出 4 个新加入的接点。
> 
> 测试期望：
> 所有节点的连接数为 3。

- [x] T015: 多节点快速加入、退出；

> 测试目的：CITA 网络可以正确处理节点并行退出同时并行加入。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 连续启动 4 个新节点，其中的已知节点配置为节点 0 的 ip : port。
> 3. 在启动节点同时，连续退出已经加入的新节点。
> 
> 测试期望：
> 所有节点的连接数为 3。

- [x] T016: 节点加入时，已知节点未启动；

> 测试目的：CITA 网络可以正确处理节点先于已知节点启动场景
> 
> 测试步骤：
> 1. 启动 4 个共识节点 （其中 node 0 先不启动），正常出块。查询所有节点连接数为 2 。
> 2. 启动新节点，其中的已知节点配置为节点 0 的 ip : port。
> 3. 启动 node 0 。
> 
> 测试期望：
> 所有节点的连接数为 4。

### 异常测试

- [x] T021: 节点加入后，已知节点重启；

> 测试目的：在已知节点重启后，新节点仍然可以重新连接已知节点。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 启动新节点，其中的已知节点配置为节点 0 的 ip : port。
> 3. 重启已知节点 0 。
> 
> 测试期望：
> 所有节点的连接数为 4 。

- [x] T022: 加入与网络中已有节点地址相同的节点；

> 测试目的：网络可以禁止伪造节点进入，或者防止同一配置的节点进入网络两次。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，正常出块。查询所有节点连接数为 3 。
> 2. 启动新节点，其中的已知节点配置为节点 0 的 ip : port；同时，其节点的 Address 与节点 1 相同。
> 
> 测试期望：
> 新节点连接被所有节点拒绝。
> 新节点的连接数为0，原有节点连接数不变。

- [x] T023: 在节点连接数到达上限时，再加入一个节点；

> 测试目的：当节点连接数达到上限时，不再接受新的接点加入。
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块。查询所有节点连接数为 3 。
> 2. 启动新节点，其中的已知节点配置为节点 0 的 ip : port 。
> 
> 测试期望：
> 新节点无法接入网络。
> 新节点的连接数为0，原有节点连接数不变。

- [x] T024: 节点连接数小于网络中的节点数；

> 测试目的：当节点连接数达到上限时，不再主动连接新的节点。
> 
> 测试步骤：
> 1. 所有节点的最大连接数设置为 2;
> 2. 启动所有节点 。
> 
> 测试期望：
> 所有节点连接数为 2。

### 正常测试

**使用加密**

- [ ] T101: 256 byte 数据一次正常传输。

> 测试目的：网络节点间可以正确传输数据；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 256 byte 数据，发送给节点 1;
> 3. 节点 1 接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应。
> 
> 测试期望：
> 节点 0 能正确接收到节点 1 的回应。

- [ ] T102: 128M 大数据包一次传输。

> 测试目的：网络节点间可以正确传输大数据包；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 128M 数据，发送给节点 1;
> 3. 节点 1 接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应。
> 
> 测试期望：
> 节点 0 能正确接收到节点 1 的回应。

- [ ] T103: 256 byte 数据连续快速传输 。

> 测试目的：网络节点间可以正确并行传输数据包；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 256 byte 数据，连续发送 1000 次给节点 1;
> 3. 节点 1 接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应, 回应计数加 1 。
> 
> 测试期望：
> 节点 0 能正确接收到 1000 次节点 1 的回应。

- [ ] T104: 256 byte 数据广播传输 。

> 测试目的：网络节点间可以正确广播数据包；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 256 byte 数据，将其广播到网络中;
> 3. 节点接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应, 回应计数加 1 。
> 
> 测试期望：
> 节点 0 能正确接收到 3 次来自其它节点的回应。

**不使用加密**

- [ ] T111: 256 byte 数据一次正常传输。

> 测试目的：网络节点间可以正确传输数据；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 256 byte 数据，发送给节点 1;
> 3. 节点 1 接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应。
> 
> 测试期望：
> 节点 0 能正确接收到节点 1 的回应。

- [ ] T112: 128M 大数据包一次传输。

> 测试目的：网络节点间可以正确传输大数据包；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 128M 数据，发送给节点 1;
> 3. 节点 1 接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应。
> 
> 测试期望：
> 节点 0 能正确接收到节点 1 的回应。

- [ ] T113: 256 byte 数据连续快速传输 。

> 测试目的：网络节点间可以正确并行传输数据包；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 256 byte 数据，连续发送 1000 次给节点 1;
> 3. 节点 1 接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应, 回应计数加 1 。
> 
> 测试期望：
> 节点 0 能正确接收到 1000 次节点 1 的回应。

- [ ] T114: 256 byte 数据广播传输 。

> 测试目的：网络节点间可以正确广播数据包；
> 
> 测试步骤：
> 1. 启动 4 个共识节点，其中所有节点的最大连接数设置为 3，正常出块 ;
> 2. 节点 0 构造 256 byte 数据，将其广播到网络中;
> 3. 节点接收到数据后，验证数据的 checksum 正确后，回应给节点 0;
> 4. 节点 0 接收 节点 1 的回应, 回应计数加 1 。
> 
> 测试期望：
> 节点 0 能正确接收到 3 次来自其它节点的回应。

### 异常测试
NA

## Additional Information

#223

**Comment by kaikai1024** [comment]
@leeyr338 Remember update your test plan first when you ready to do this issue and drag it to the `in-progress`.

**Comment by kaikai1024** [comment]
Just the plan.

**Comment by leeyr338** [comment]
Network 模块当前有两个关键的功能：

- 节点发现：当一个节点接入网络时，可以自动发现其它节点，并接入网络。
- 数据传输：将本节点的数据发送给相连的节点。

测试方案设计主要针对这两个关键工能展开。

**Comment by leeyr338** [comment]
## 节点发现测试 （WIP）

### 正常测试
**不使用域名测试**

- [ ] 单节点正常节点加入；

- [ ] 单节点节点正退出；

- [ ] 多节点快速加入；

- [ ] 多节点快速退出；

- [ ] 多节点快速加入、退出；

- [ ] 节点加入时，已知节点未启动；

**使用域名**

- [ ] 单节点正常节点加入；

- [ ] 单节点节点正退出；

- [ ] 多节点快速加入；

- [ ] 多节点快速退出；

- [ ] 多节点快速加入、退出；

- [ ] 节点加入时，已知节点未启动；

- [ ] 节点加入后，已知节点重启；

### 异常测试

- [ ] 节点加入后，已知节点重启；

- [ ] 加入与网络中已有节点地址相同的节点；

- [ ] 加入一个已知节点配置错误的节点；

- [ ] 在节点连接数到达上限时，再加入一个节点；

## 数据传输测试

### 正常测试

**使用加密**

**不使用加密**


### 异常测试

**Comment by kaikai1024** [comment]
> 节点发现测试 （WIP）

You can edit it on the issue description part.

**Comment by kaikai1024** [comment]
https://github.com/bitcoin/bitcoin/tree/master/test/functional
