### ISSUE TITLE
Add command line arguments to display algorithms (crypto and hash)

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#376]
How to know the algorithms (crypto and hash) if I only have binary files?

These information should display in `--help` or `--version`.

**Comment by kaikai1024** [comment]
yeah, you are right.

**Comment by driftluo** [comment]
It can do like this:
https://github.com/cryptape/cita-cli/blob/fb5825fecdae3f972fde49b368a1438149164c80/cita-cli/src/main.rs#L81:L91
