### ISSUE TITLE
Can't generate block when add a consensus node. ## 新增共识节点，导致链不出块

### ISSUE THREAD

**Issue by mingxiaowu** [cryptape/cita#381]
## Description

approveNode 后，链不出块

## Steps to Reproduce

1. approveNode 一个已经是共识节点的 address
2. approveNode 一个共识节点，address 为一个已经共识的address 修改最后一位或两位。（不确定步骤1和2有没有必然联系；如果不能复现，多操作几次步骤2）

**Actual behavior**: 

不出块

## Versions

v0.22.0

**Comment by leeyr338** [comment]
最后的共识节点数是几个？

**Comment by mingxiaowu** [comment]
原因：
1.approve一个不存在的address，交易成功；
2.再approve一个不存在的address，交易成功；（NodeManager listNode --height pending ，可以显示出该共识节点）
3.节点均未启动，没有超过2/3，所以不出块是合理的；
