### ISSUE TITLE
How about using `sentry`?

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#383]
## Description

For  error reporting.

## Additional Information

https://github.com/getsentry/sentry

**Comment by yangby-cryptape** [comment]
**Important**: Should be optional and default should be disable.
We should do our best to protect user's privacy.

Or only enable in development version.

**Comment by kaikai1024** [comment]
> We should do our best to protect user's privacy.

yeah.

**Comment by kaikai1024** [comment]
Use [before_send](https://getsentry.github.io/sentry-rust/sentry/struct.ClientOptions.html#structfield.before_send) to print stack info.

**Comment by jerry-yu** [comment]
done
