### ISSUE TITLE
Will stuck when setup the second node on one machine. ## 摘要：【CITA】在同一台机器上setup4个节点，setup第二个节点时会卡住。

### ISSUE THREAD

**Issue by wangfh666** [cryptape/cita#384]
摘要：【CITA】在同一台机器上setup 4个节点，setup第二个节点时会卡住。

前提条件：
1、在同一台机器上运行；

操作步骤：
1、初始化一条链；
2、初始化成功后，进行setup操作；
3、先setup第一个节点，第一个节点setup成功后，对第二个节点进行setup操作，查看 --KO；

预期结果：可以正常进行配置操作。

实际结果：当对第二个节点进行setup操作后，会卡住。
![代码截图](https://user-images.githubusercontent.com/41322861/55309505-972f6400-5490-11e9-98ca-9b4eb8e91852.png)

**Comment by ouwenkg** [comment]
Which version?

**Comment by kaikai1024** [comment]
I've tried latest develop version on my own pc.
And it's normal.
Need more information.

**Comment by wangfh666** [comment]
@ouwenkg 最新版本，就是有开发改了截图中的代码，日志输出到了前台，导致使用cli命令执行操作时，拿不到日志，一直处于卡住状态

**Comment by kaikai1024** [comment]
> 就是有开发改了截图中的代码，日志输出到了前台

能不能截一下 第二个 setup 卡住的图?

**Comment by wangfh666** [comment]
<img width="1268" alt="操作截图" src="https://user-images.githubusercontent.com/41322861/55527388-66873e80-56cb-11e9-9a5d-28884cba72f5.png">
就是执行类似的docker exec -i 命令，控制台输出结果，但是不自动终止

**Comment by kaikai1024** [comment]
1. 你描述 的第二个 setup ，如果没有 start，是不会运行到你截图里面的代码的。

2. 类似结果的截图其实帮助不大，麻烦原始情形的截图或者复现的截图，谢谢

**Comment by wangfh666** [comment]
截图待会上，这个问题我们在流水线上运行我们的测试代码，使用cli实现的测试代码都会卡住

**Comment by ouwenkg** [comment]
#401
