### ISSUE TITLE
Can not exit when run `bin/cita` after start the chain.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#385]
## Description

![Screenshot from 2019-04-01 15-31-36](https://user-images.githubusercontent.com/8768261/55310551-49682b00-5493-11e9-9f23-9b55b3877a04.png)

## Steps to Reproduce

1. Start the chain
2. Run `bin/cita`

**Expected behavior**: 

exit and back to the terminal.

**Actual behavior**: 

can not exit, even with `ctrl + c`

**Reproduce how often**: not sure(will try more times)

## Versions

develop

**Comment by ouwenkg** [comment]
Well, I encounted the same situation with you.

**Comment by kaikai1024** [comment]
because of the `bin/cita start test-chain/0` command.
`daemon`

**Comment by u2** [comment]
> because of the `bin/cita start test-chain/0` command.
> `daemon`

Could you explain it more clearly? I did not get it.

**Comment by kaikai1024** [comment]
> Could you explain it more clearly?

Still be finding the reason. daemon is just the situation.

`-d`  to use the docker then  `-i` can not exit.

**Comment by yangby-cryptape** [comment]
`docker exec -it` will hang if there is any daemon process which hold the `stdout`.
(no reason for this, you can consider it is a bug or a feature)

We should redirect the `stdout` and `stderr` for `daemon processes`.

https://github.com/cryptape/cita/blob/5df437406fe4c885cbc3554004b254570b12b8c1/env.sh#L74-L80
