### ISSUE TITLE
develop 分支commit dc45dca  编译失败 

### ISSUE THREAD

**Issue by jiangxianliang007** [cryptape/cita#389]
` > /usr/bin/git checkout -f dc45dca5241498ecafc3c89330f077c2aaad2b56
Commit message: "Installation && Exectution Optimization.  (#334)"
 > /usr/bin/git rev-list --no-walk 7e3035fdb36eff5735708bb4440ed7372865b02e # timeout=10
No emails were triggered.
[build-cita-bin] $ /usr/bin/env bash /tmp/jenkins2036315476652059040.sh
git revison dc45dca5241498ecafc3c89330f077c2aaad2b56
79a06b5df798
Start docker container cita_build_container ...
WARNING: Published ports are discarded when using host network mode
0e3991d9f0e00b1fcc4c790ee7bfc91bff53637d33663805190fc4559e7b20b5
RUSTFLAGS='-F warnings' cargo build --all  --release
    Updating git repository `https://github.com/cryptape/cita-common.git`
    Updating `https://mirrors.ustc.edu.cn/crates.io-index` index
    Updating git repository `https://github.com/nervosnetwork/p2p.git`
    Updating git repository `https://github.com/cryptape/zktx.git`
    Updating git repository `https://github.com/cryptape/hyper.git`
    Updating git repository `https://github.com/cryptape/libsm`
    Updating git repository `https://github.com/cryptape/bellman.git`
    Updating git repository `https://github.com/cryptape/jubjub-prototype.git`
    Updating git repository `https://github.com/cryptape/pairing.git`
    Updating git repository `https://github.com/cryptape/tokio-proto.git`
    Updating git repository `https://github.com/fede1024/rust-rdkafka.git`
 Downloading crates ...
  Downloaded crossbeam-channel v0.3.8 (registry `https://mirrors.ustc.edu.cn/crates.io-index`)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
  Downloaded num v0.1.42 (registry `https://mirrors.ustc.edu.cn/crates.io-index`)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
  Downloaded ethabi v4.2.0 (registry `https://mirrors.ustc.edu.cn/crates.io-index`)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates)
error: failed to download from `https://crates-io.proxy.ustclug.org/api/v1/crates/rust-crypto/0.2.36/download`

Caused by:
  [6] Couldn't resolve host name (Could not resolve host: crates)
make: *** [release] Error 101
Makefile:10: recipe for target 'release' failed`

https://crates-io.proxy.ustclug.org/api/v1/crates/rust-crypto/0.2.36/download 这个地址不能正常访问 状态为 404

**Comment by yangby-cryptape** [comment]
Try the official source.

**Comment by kaikai1024** [comment]
#390 

Maybe remove the ustc sources.
