### ISSUE TITLE
I built failed when I use `ustc` sources, the same issue can refer to [#6513][1] in cargo.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#390]
I am not sure about these lines, I built failed when I use `ustc` sources, the same issue can refer to [#6513][1] in cargo.

[1]: https://github.com/rust-lang/cargo/issues/6513

_Originally posted by @clearloop in https://github.com/cryptape/cita/pull/334/files_

**Comment by kaikai1024** [comment]
Remove the ustc source. and add the doc about replacing resource.

**Comment by clearloop** [comment]
I'll do more investigation about the `ustc` source late days.
