### ISSUE TITLE
Please use functions and local variables for whole shell scripts

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#395]
Please use functions and local variables for whole shell scripts.

An example:

https://github.com/cryptape/cita/blob/654c49f44776eb04cd6614c977b4ae7593eeb92d/tests/integrate_test/cita_crosschain.sh#L548

So, we can check each variables clearly.

**Comment by yangby-cryptape** [comment]
I do not accept only a `art` label for this.
Bugs are always hiding in untidy code, and they are difficult to find in review phase.

We should pay attention to it.

**Comment by kaikai1024** [comment]
> I do not accept only a art label for this.

yeah, we should follow a unified guide

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita/wiki/Style-Guide#shell

Will update to the style-guide folder after collecting more guides.
