### ISSUE TITLE
***Code Style***

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#398]
## Description

Add the style-guide folder and a wiki.

* [x] The code style of Rust
* [x] The code style of Shell
* [x] The code style of Python
* [x] The code style of JavaScript
* [x] The code style of Solidity

## Additional Information

#395 

https://google.github.io/styleguide/shell.xml
https://github.com/rust-dev-tools/fmt-rfcs/blob/master/guide/guide.md
https://github.com/RetroPie/RetroPie-Setup/wiki/Shell-Style-Guide
https://github.com/koalaman/shellcheck

**Comment by yangby-cryptape** [comment]
:+1:

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita/wiki/Style-Guide
