### ISSUE TITLE
Unable to resolve host linuxkit-025000000001

### ISSUE THREAD

**Issue by superman-dongyanjie** [cryptape/cita#399]
## Description

Error when run `./env.sh ./bin/cita setup test-chain/0`

## Versions

v0.22.0

MacOS

**Comment by kaikai1024** [comment]
More info, Please

**Comment by superman-dongyanjie** [comment]
release 版本 按文档说明执行失败

error:
        sudo: unable to resolve host linuxkit-025000000001

**Comment by superman-dongyanjie** [comment]
执行命令为：
        ./env.sh ./bin/cita setup test-chain/0

**Comment by kaikai1024** [comment]
什么操作系统？

**Comment by superman-dongyanjie** [comment]
mac  + docker

**Comment by kaikai1024** [comment]
@leeyr338 

`env.sh` 脚本里--net=host` 删除，增加 `-p 1337:1337 \`

**Comment by superman-dongyanjie** [comment]
依然报相同的错误：
sudo: unable to resolve host linuxkit-025000000001

env.sh 脚本，docker run 部分，修改后代码：
docker ps | grep ${CONTAINER_NAME} > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Start docker container ${CONTAINER_NAME} ..."
    docker rm ${CONTAINER_NAME} > /dev/null 2>&1
    docker run -d \
           -p 1337:1337
           --volume ${RELEASE_DIR}:${WORKDIR} \
           --volume ${LOCALTIME_PATH}:/etc/localtime \
           --env USER_ID=${USER_ID} \
           --workdir ${WORKDIR} \
           --name ${CONTAINER_NAME} ${DOCKER_IMAGE} \
           /bin/bash -c "while true;do sleep 100;done"
    # Wait entrypoint.sh to finish
    sleep 3
fi

**Comment by kaikai1024** [comment]
删掉旧的容器，试下

* `docker ps`
* docker rm `

**Comment by superman-dongyanjie** [comment]
删除旧的容器，重启docker后成功，66666

**Comment by kaikai1024** [comment]
谢谢使用，我们会尽快添加 Mac 更友好的支持
