### ISSUE TITLE
Add Vagrantfile for easy development

### ISSUE THREAD

**Issue by adrianbrink** [cryptape/cita#4]

**Comment by poshboytl** [comment]
Thanks for the suggestion.
I think both Docker & Vagrant will be supported.

**Comment by poshboytl** [comment]
@wsnbbxy Please help on the Docker support, thanks.

**Comment by poshboytl** [comment]
The docker support is good to use for development now.  

https://github.com/cryptape/cita/blob/develop/docs/source/bootstrap.rst
