### ISSUE TITLE
Using docker-compose to deploy CITA, once the node is shut down after boot-up, it will not be able to boot up properly again.###使用docker-compose部署CITA,启动后一旦关闭节点，再次启动无法正常出块

### ISSUE THREAD

**Issue by zhjgit** [cryptape/cita#407]
一.部署环境
     一台ubuntu16.04 服务器部署4个节点cita链

二.操作步骤。
    1.准备cita部件，v0.19.1

```
#!/bin/bash
echo "latest release tag: v0.19.1"
wget https://github.com/cryptape/cita/releases/download/v0.19.1/cita_secp256k1_sha3.tar.gz
tar zxvf cita_secp256k1_sha3.tar.gz
cp -r cita_secp256k1_sha3 cita_secp256k1_sha3_node0
cp -r cita_secp256k1_sha3 cita_secp256k1_sha3_node1
cp -r cita_secp256k1_sha3 cita_secp256k1_sha3_node2
cp -r cita_secp256k1_sha3 cita_secp256k1_sha3_node3

wget https://raw.githubusercontent.com/cryptape/cita/develop/tests/integrate_test/docker-compose.yaml
```

     2.部件下载后，启动cita

```
USER_ID=`id -u $USER` docker-compose up
```

     3.停止cita 

```
         CTRL+C   
```

    4.再次启动cita

```
  USER_ID=`id -u $USER` docker-compose up -d
```

    不能正常出块，块高卡在上次停止的地方。
![image](https://user-images.githubusercontent.com/11417141/55467430-de098f00-5633-11e9-9eb8-7cdcf364e17a.png)

**Comment by leeyr338** [comment]
我按照上面的命令，是可以出块的，但没有加 `-d`。
加完`-d` 后，也出不了块。

**Comment by kaikai1024** [comment]
看看其他们模块的日志

https://docs.citahub.com/zh-CN/cita/getting-started#%E4%BD%BF%E7%94%A8docker-compose

有停止的命令， 是不是因为 ctrl + c 的原因

**Comment by leeyr338** [comment]
docker-compose使用了docker的域名系统。我觉得与下面的这个issue相关：
https://github.com/cryptape/cita/issues/250
这个问题在v0.22.0才合入解决，我今天尝试用v0.22.0看一下。

**Comment by zhjgit** [comment]
我看了 #250 的issue 可能跟那个问题相关，要是还存在不能正常出块，我就先用docker启动4个节点跑

**Comment by rink1969** [comment]
之前碰到过解析IP的问题，但是0.19.1是没有这个问题的。
只要成功过一次就可以排除这个问题了。
看问题描述第一次是成功的，就可以排除这个原因了。

看下network日志吧，如果重启之后网络不通。
可能的原因是docker的虚拟网络问题。
建议不要ctrl+c，用正常的结束命令。
如果还是不行，建议重启docker服务。

另外建议ps看一下进程数是否正常。
一个可能的原因是ctrl+c结束，没有清理.pid文件。
下次启动的时候，如果pid刚好跟上次相同，可能会误认为进程已经存在。

正常的结束流程是先 cita stop 每个节点
然后docker compose shutdown。

**Comment by leeyr338** [comment]
详细看了一下，这里有两个问题：
1. 域名解决时存在 bug, 会导致在某些场景下节点连接不成功，见 #250 描述。需要使用 v0.22.0 版本解决。
2. 使用 docker compose 时，是不会删除节点配置的 .*.pid文件的，这个会导致有些微服务启动不了。解决方法，需要手工删除一下其中的.*.pid文件。如：
```
$ ls cita_secp256k1_sha3_node0/test-chain/0/ -a
.   address    chain.toml      .cita-bft.pid    .cita-executor.pid  .cita-jsonrpc.pid  consensus.toml  .env           forever_mock.toml  genesis.json  logs          privkey
..  auth.toml  .cita-auth.pid  .cita-chain.pid  .cita-forever.pid   .cita-network.pid  data            executor.toml  forever.toml       jsonrpc.toml  network.toml
```

**Comment by kaikai1024** [comment]
> 使用 docker compose 时，是不会删除节点配置的 ..pid文件的，这个会导致有些微服务启动不了。解决方法，需要手工删除一下其中的..pid文件

有办法 fix 吗？不行就添加到 [faq](https://docs.citahub.com/zh-CN/next/cita/ref/faq)
