### ISSUE TITLE
suicide instruction gas price

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#418]
# Suicide instruction gas price

## Description

Different instruction gas price:

```
suicide_gas                // cita=0, parity=5000
suicide_to_new_account_cost // cita=0, parity=25000
```
Imaging a account with 21000 gas (only basical gas require), he want to launch a transaction
do suicide operation. 

This transaction works well in CITA, since the suicide gas is zero.
This transaction failed in Ethereum and return `Out of Gas`

**Comment by ouwenkg** [comment]
#366

**Comment by kaikai1024** [comment]
Maybe we should consider to upgrade the version to fix it

**Comment by ouwenkg** [comment]
Yeap，Agreed with you. No matter fix it or not, It's better to dive into the deep reason in future.

**Comment by ouwenkg** [comment]
| Instruction | CITA | ETH|
|---------------| -------| -------|
| call_gas | 40 | 700 |
| balance_gas | 20 | 400 |
| exp_byte_gas| 10 | 50 |
| suicide_gas | 0 | 5000 |
| suicide_to_new_account_cost | 0 | 25000|

References:
[EIP 150](http://eips.ethereum.org/EIPS/eip-150)
[EIP 160](http://eips.ethereum.org/EIPS/eip-160)

**Comment by kaikai1024** [comment]
Close it temporarily.
