### ISSUE TITLE
Update `gosu` in docker

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#420]
New version was released and `gosu` can be installed via `apt` (I have test for `ubuntu:bionic`).

Ref:
- [Installation of `gosu`: from debian](https://github.com/tianon/gosu/blob/master/INSTALL.md#from-debian)
- [Installation of `gosu`: in cita-build](https://github.com/cryptape/cita-build/blob/ubuntu-18.04-20190304/Dockerfile#L69-L93)
- [Installation of `gosu`: in cita-run](https://github.com/cryptape/cita-run/blob/ubuntu-18.04-20190313/Dockerfile#L43-L67)

**Comment by kaikai1024** [comment]
nice
