### ISSUE TITLE
Update P2P library

### ISSUE THREAD

**Issue by leeyr338** [cryptape/cita#424]
## Description

Update P2P library to 0.2 alpha 2.

This version is using a different discovery mechanism. 
It is a break change for CITA, so it MUST be updated in CITA alpha.

**Comment by kaikai1024** [comment]
We have three or five pre-release version of v1.0.0

**Comment by driftluo** [comment]
I prefer to upgrade. Currently, some branches of `cita` dependencies has some errors don't report to user users, and the `flatbuffer` verification has the possibility of panic. There is a possibility of being attacked

**Comment by kaikai1024** [comment]
> I prefer to upgrade

yeah, we'll follow the library to the release version instead of the pre-release. 
while we'll focus on the vm-test and state-test at this version(alpha). 

> and the flatbuffer verification has the possibility of panic

we'll discuss it this morning and update the decision

**Comment by leeyr338** [comment]
New version has been released:
https://crates.io/crates/tentacle/0.2.0-alpha.2
