### ISSUE TITLE
The tool to check the license.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#428]
## Description

We need a tool to scan the license.

## Additional Information

* https://fossa.com/
* https://fossid.com/
* `cargo license`

#348

**Comment by leeyr338** [comment]
Can we use [cargo license](https://github.com/onur/cargo-license) ?
Maybe fossa is more professional, but I have not tried it out.

**Comment by kaikai1024** [comment]
I've tried the `cargo license`, it seems that it can only scan the crates:

```
N/A (46): engine, evm, chain-executor-mock, panic_hook, cita-types, fuchsia-cprng, cita-relayer-parser, jsonrpc-proto, cita-jsonrpc, authority_manage, chain-performance-by-mq, cita-forever, hashable, common-types, cita-auth, jsonrpc-types-internals, snappy, cita-secp256k1, rlp_derive, error, libproto, cita-directories, core, ring, create-key-addr, proof, box-executor, cita-merklehash, cita-bft, db, cita-network, cita-crypto-trait, cita-ed25519, tx_pool, pubsub_rabbitmq, core-executor, pubsub, cita-executor, snapshot-tool, util, cita-crypto, state-test, consensus-mock, cita-chain, create-genesis, jsonrpc-types
```

**Comment by leeyr338** [comment]
Yes, have you tried fossa?

**Comment by kaikai1024** [comment]
> Yes, have you tried fossa?

No, need a research.

**Comment by kaikai1024** [comment]
FOSSA:

> Known Limitations:
>
> * Optional dependencies are currently handled like Java optional dependencies, when they should be enabled/disabled based on features
> * FOSSA does not currently understand default/missing features
> * FOSSA does not handle path dependencies that point above your repo root

**Comment by jerry-yu** [comment]
use fossa
