### ISSUE TITLE
v0.21.1 no block after node migration ## v0.21.1 链在节点迁移后不出块

### ISSUE THREAD

**Issue by leeyr338** [cryptape/cita#431]
## Description
v0.21.1 链在节点迁移后不出块

CITA 节点从一个物理节点迁移到别一个物理节点后，在连续发送转帐交易时，链不出块。

## Steps to Reproduce
1. 在物理机 (node0) 上启动一条 4 个共识节点的链；启动发送转账交易程序 (每秒 4 笔交易)。

2. 在步骤 1 执行一段时间后，在物理机 (node2) 上启动另外 4 个 CITA 节点，并将其中两个设为共识节点。

3. 在步骤 2 执行一段时间后，node2 宕机，将其上的 4 个 CITA 节点迁移到 node0 上。

4. 链不出块，重启所有 CITA 节点多次，链仍然不出块。

**Expected behavior**: 
链正常出块

**Actual behavior**: 
链不出块

**Reproduce how often**: 
在不出块时开始定位问题，没有从头开始再执行一次。

## Versions
v0.21.1

## Additional Information
- 节点的启动操作，参考官网的 [使用docker-compose](https://docs.citahub.com/zh-CN/cita/getting-started) 。

- 链块高度121050

**Comment by leeyr338** [comment]
查看日志，发现多个 CITA 的节点中的 `auth` 服务反复重启，日志为：
![image](https://user-images.githubusercontent.com/38514341/55859710-30532e80-5ba5-11e9-9f3d-56213f08fa05.png)
当出现 `auth is not ready` 时，`auth` 服务便出现重启。
这是一个[已知问题](https://github.com/cryptape/cita/pull/328)，需要在 v0.22.0 版本才修复。

**Comment by leeyr338** [comment]
切换到 v0.22.0 版本后，发现链仍然不出块。

由于在 v0.21.1 上反复重启了链，导致最后一个块的共识出现问题。
使用工具将最后出现共识出错问题的块去除后，链恢复正常。

**Comment by jerry-yu** [comment]
因为使用的是compact proposal，某交易只在node1校验有效，其它node因为auth的不停重启，丢失了该交易，导致一直校验不通过。再加上一个节点没有到当前round，node1 lock 在包含某交易的proposal上，导致6个共识节点，只有四个节点一致，没法达成共识。
