### ISSUE TITLE
make release error

### ISSUE THREAD

**Issue by dis-happy** [cryptape/cita#44]
error: failed to run custom build command for `libsodium-sys v0.0.14 (https://github.com/cryptape/sodiumoxide.git#c324e11a)`
process didn't exit successfully: `/opt/export/app/evm-cita/cita/target/release/build/libsodium-sys-835e5eb911e0ed28/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: No such file or directory (os error 2)"', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
Makefile:20: recipe for target 'release' failed
make: *** [release] Error 101

**Comment by u2** [comment]
@vinberm

**Comment by suyanlong** [comment]
Are your OS ubuntu16.04?  You can look Makefile or, sudo  apt install libsodium*

**Comment by vinberm** [comment]
sudo apt-get install libsodium* @dis-happy

**Comment by u2** [comment]
sudo apt-get install libsodium18 libsodium-dev pkg-config
