### ISSUE TITLE
Upgrade Rust Toolchain: `TryFrom` & `TryInto` are stable

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#444]
The rust v1.34.0 is released!

According to the official rust blog, [`TryFrom` & `TryInto` are stable] since `rust v1.34.0`.

So, any plan to upgrade the rust toolchain?

We can use the official traits to replace custom traits.

For example:

https://github.com/cryptape/cita/blob/35e66490dfa84b4b34f6aa49c87fd3783e601b25/cita-chain/src/forward.rs#L34

[`TryFrom` & `TryInto` are stable]: https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html#tryfrom-and-tryinto

And, Maybe we should add `rust-toolchain` in root of CITA. Write the real version (`1.34.0`) into the file.

* [x] The image is ready
* [ ] Upgrade the toolchain

**Comment by kaikai1024** [comment]
We'll follow the stable version of Rust.
