### ISSUE TITLE
Link with system rocksdb and snappy libs through envvars 

### ISSUE THREAD

**Issue by yangby-cryptape** [cryptape/cita#456]
Maybe we can update the Dockerfile of `cita-build`:
- [ ] Add `librocksdb-dev`.
- [ ] Add environment variables.

Can reduce a lot of compile time.

Ref: [Rust-RocksDB PR-166: Link with system rocksdb and snappy libs through envvars](https://github.com/rust-rocksdb/rust-rocksdb/pull/166)

**Comment by kaikai1024** [comment]
We use the `parity-rocksdb`
