### ISSUE TITLE
[WebSocket] Keeps track of open sessions to support pub/sub

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#463]
**Is your feature request related to a problem? Please describe.**

Can't use pub/sub mode to use getLogs.

**Describe the solution you'd like**

Keeps track of open sessions to support pub/sub

**Describe alternatives you've considered**

None

**Additional context**

https://docs.rs/jsonrpc-ws-server/11.0.0/jsonrpc_ws_server/

**Comment by jerry-yu** [comment]
to be consider
