### ISSUE TITLE
base_gas_required calculate problem

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#466]
## base_gas_required calculate problem

Usually, before transaction executed in vm, some basic will be consumed firstly. 
For example, if you send a transaction to create a contract, 53000 quotas will be consumed before this tx enters vm, so please ensure your gas > base_gas while sending transaction.

Base_gas calculation in ethereum:
> gas_prepare = 21000 + (68 or 4 per byte) + (32000 if tx.to == 0)

Implement in cita_vm as following:
```
pub fn get_gas_prepare(request: &InterpreterParams) -> u64 {
    let mut gas_prepare: u64 = 0;
    gas_prepare += G_TRANSACTION;
    if request.is_create {
        gas_prepare += G_CREATE
    }
    for i in &request.input {
        if i == &0u8 {
            gas_prepare += G_TX_DATA_ZERO
        } else {
            gas_prepare += G_TX_DATA_NON_ZERO
        }
    }
    gas_prepare
}
```

Implement in cita_vm like this:
```
pub fn get_gas_prepare(request: &InterpreterParams) -> u64 {
    let mut gas_prepare: u64 = 0;
    gas_prepare += G_TRANSACTION;
    if request.is_create {
        gas_prepare += G_CREATE
    }
    gas_prepare
}
```

Did you find difference between above two calculation? 

In CITA, we indeed have two related instructions `tx_data_zero_gas` and `tx_data_non_zero_gas`. However, we do nothing in basic gas calculation with code.

## Additional Information

#366

**Comment by kaikai1024** [comment]
I remember that the base required is added with the `charge` feature.

Not sure about this.

**Comment by ouwenkg** [comment]
https://github.com/cryptape/cita/blob/develop/cita-executor/core/src/externalities.rs#L383

`fn ret(mut self, gas: &U256, data: &ReturnData, apply_state: bool) -> evm::Result<U256>` 
该处扣费旨在处理 `Return` 指令返回的数据.  

接口见 https://github.com/cryptape/cita/blob/develop/cita-executor/evm/src/ext.rs#L114

@leeyr338
