### ISSUE TITLE
`ERROR` level of default function of `contracts/solc`

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#471]
## Description

Look into it.

~~Why can not get the quota price?~~

including all the contracts:

* [x] Use `info`
* [x] Add unit test

## Additional Information

https://talk.citahub.com/t/topic/524

**Comment by kaikai1024** [comment]
Reason:

https://github.com/cryptape/cita/blob/develop/cita-executor/core/src/libexecutor/sys_config.rs#L187

**Comment by ouwenkg** [comment]
Changing log level could solve this problem?

**Comment by kaikai1024** [comment]
Actually, it's not a problem.

default function should show the default value, the error message should be in the call function.
