### ISSUE TITLE
Log segmentation generates directory changes

### ISSUE THREAD

**Issue by QingYanL** [cryptape/cita#485]
- before 
`./env.sh ./bin/cita logrotate test-chain/0`
 
./test-chain/0/logs/cita-auth_2018-04-02_11-34-51.log

- now
`/bin/cita logrotate test-chain/0`

/opt/cita/test-chain/0/logs/cita-auth_2019-04-19_10-50-06.log
**This directory is only available in docker**

**Comment by kaikai1024** [comment]
> /opt/cita/test-chain/0/logs/cita-auth_2019-04-19_10-50-06.log

It showed the wrong info. actually, it worked and you can find it at the `test-chains/0/logs/`
I'll fix that.

**Comment by leeyr338** [comment]
> > /opt/cita/test-chain/0/logs/cita-auth_2019-04-19_10-50-06.log
> 
> It showed the wrong info. actually, it worked and you can find it at the `test-chains/0/logs/`
> I'll fix that.

How about shows it as a relative path, like:
```
test-chain/0/logs/cita-auth_2019-04-19_10-50-06.log
```
?

**Comment by kaikai1024** [comment]
> How about shows it as a relative path

ok. 

Need to find out why shows the path of container instead of actual local path.

**Comment by leeyr338** [comment]
This because, `cita` run the scripts in **docker**:

```
NODE_PATH="$(dirname $CITA_BIN)/${NODE_NAME}"
```

And this command should be run in **docker**.

**Comment by mingxiaowu** [comment]
<img width="447" alt="bug-fix-now" src="https://user-images.githubusercontent.com/42978282/56791812-980ea800-683a-11e9-904a-b68fc3348bbd.png">

**Comment by kaikai1024** [comment]
> v0.23,验证，如图

和预期一致
