### ISSUE TITLE
Node doesn't work well after get rpc request getLogs with a big param of toBlock.

### ISSUE THREAD

**Issue by luqz** [cryptape/cita#494]
## Description

Node doesn't work well after get rpc request getLogs with a big param of to.

## Steps to Reproduce

1. create and start a test-chain;
2. use rpc method getLogs, and param `toBlock ` is very big, like 0xffffffffffffff;

**Expected behavior**: 
1.  Return array or error message, 
2. The node works well.

**Actual behavior**: 
1.  Return error message: system timeout, 
2. Module cita-chain keep use more than 90% of CPU,
3. The node almost doesn't work.

**Reproduce how often**: 
every time.

## Versions

v0.22.0

**Comment by leeyr338** [comment]
>> use rpc method getLogs, and param to is very big, like 0xffffffffffffff;

This is no `to` param for `getLogs`, see
https://docs.citahub.com/zh-CN/cita/rpc-guide/rpc#getlogs

Would you please show me the exactly `curl` command for your JSON-RPC call.

**Comment by leeyr338** [comment]
From @jerry-yu 
jsonrpc的getlogs接口，可能获取的logs可能会超级大。
logs编码设置进入response，占用chain很多内存，
可能会导致内存不足.

另外还有一个思考就是：业务发送new filterlog，然后chain重启了，业务层感知不到，没有继续发送new filterlog，可能就没法准确的获得 change logs了

**Comment by kaikai1024** [comment]
> This is no to param for getLogs,

it does have.

This is no to param for getLogs,

**Comment by kaikai1024** [comment]
Does it hapen if `to` is `latest`?

**Comment by leeyr338** [comment]
> Does it hapen if to is latest?

It works for latest.

**Comment by mingxiaowu** [comment]
v0.23 验证通过
