### ISSUE TITLE
snapshot don't take effect

### ISSUE THREAD

**Issue by QingYanL** [cryptape/cita#496]
## Description

[Description of the issue]
snapshot don't take effect

## Steps to Reproduce

1.  **exec in mac**   
`cd /test-chain/0`
`../../bin/snapshot_tool -m snapshot -e 100`
output: **-bash: ../../bin/snapshot_tool: cannot execute binary file**
2. `ls -l snapshot_tool`
output: **-rwxr-xr-x@ 1 yanli  staff  9901816  4 19 01:36 snapshot_tool**

![image](https://user-images.githubusercontent.com/48231505/56551965-540e6f80-65bc-11e9-8c22-21a91fc1a9dd.png)

3. **exec in docker**   
`cd /test-chain/0`
`../../bin/snapshot_tool  -m snapshot -e 100`
`ls snap*`
output:  **ls: cannot access 'snap': No such file or directory**

![image](https://user-images.githubusercontent.com/48231505/56552013-77d1b580-65bc-11e9-88cf-be1880f89cd5.png)

**Expected behavior**: [snapshot take effect]

**Actual behavior**: [snapshot don't take effect]

**Reproduce how often**: [every time]

## Versions

[develop]

**Comment by ouwenkg** [comment]
Two problems:
1. `-bash: ../../bin/snapshot_tool: cannot execute binary file`, it only occured in mac os. Platform difference causes this error. It's recommend to run such command in docker.
2. `ls snap*` and return no result. That a bug in snapshot module, the process will panic if we use default file path. #500  will fix it.

@QingYanL Check it.
