### ISSUE TITLE
v0.23编译报错

### ISSUE THREAD

**Issue by mingxiaowu** [cryptape/cita#497]
## Description
根据文档步骤，编译 release-0.23.0，失败
[Description of the issue]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on …]

**Expected behavior**: [What you expect to happen]

**Actual behavior**: [What actually happens]
<img width="1439" alt="20190423" src="https://user-images.githubusercontent.com/42978282/56552406-c2076680-65bd-11e9-9b66-8dc8e03bcedf.png">

**Reproduce how often**: [What percentage of the time does it reproduce?]

## Versions
release-0.23.0
[The versions of the CITA, operating systems or VM software you use]

## Additional Information

[Any other information which would be helpful to reproduce the issue].

**Comment by kaikai1024** [comment]
Please add the OS info.

**Comment by ouwenkg** [comment]
I don't need `env.sh` any more while compiling cita, just `make` is ok in my os.

**Comment by kaikai1024** [comment]
> I don't need env.sh any more while compiling cita, just make is ok in my os.

Because you have the build environment. That's what `env.sh` script does.

**Comment by leeyr338** [comment]
You've got error message:
![屏幕快照 2019-04-23 下午2 38 03](https://user-images.githubusercontent.com/38514341/56560013-d8b9b780-65d5-11e9-8051-95628508a90e.png)


Please install `coreutils` in your macOS and try again, see https://talk.citahub.com/t/topic/552:
```
brew install coreutils
```

**Comment by kaikai1024** [comment]
@mingxiaowu Would you please try it again?

**Comment by mingxiaowu** [comment]
brew install coreutils 之后，编译成功，thanks。
