### ISSUE TITLE
mac ports mapping does not work

### ISSUE THREAD

**Issue by QingYanL** [cryptape/cita#515]
## Description

[mac port mapping does not work]

## Steps to Reproduce

1. `./bin/cita  port 1338:1338 1339:1339 1340:1340`
![image](https://user-images.githubusercontent.com/48231505/56798573-95677f00-6849-11e9-9ec6-e3cd235dd6c3.png)
2.` ./bin/cita port 1338:1338`
![image](https://user-images.githubusercontent.com/48231505/56798755-03ac4180-684a-11e9-91e2-7d6f6de94bc7.png)

**Expected behavior**: [support mac multiple port mapping]

**Actual behavior**: [only support one port mapping]

**Reproduce how often**: [every]

## Versions

[develop v0.23]

**Comment by kaikai1024** [comment]
Not a bug.
Only support one port mapping now.
Please new a feature-request issue.
