### ISSUE TITLE
Can not get the history block data after restore snapshot. ## 快照恢复不生效，查询不到快照块内的历史数据

### ISSUE THREAD

**Issue by QingYanL** [cryptape/cita#531]
## Description
[快照恢复不生效，查询不到快照块内的历史数据]
## Steps to Reproduce
1. 起链：
`bin/cita create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003" --contract_arguments SysConfig.economicalModel=1`

2. 转账：
`transfer --address 0x0d5c23dc41956c8aca3b6f3fa581a4fd640f7997 --private-key 0x5f0258a4778057a8a7d97809bd209055b2fbafa654ce7d31ec7191066b9225e6 --value 1000`

获取回执信息
`rpc getTransactionReceipt --hash 0x1270429754fe3fb2dbb65538da9e9de2b0f83fe3ba7316b4dee6844919a360fc`
**快高：  0x40   64块高**
![image](https://user-images.githubusercontent.com/48231505/56876099-a4cc0f80-6a77-11e9-8b5d-102cbb1b02bb.png)

获取账户余额
`rpc getBalance --address 0x0d5c23dc41956c8aca3b6f3fa581a4fd640f7997`

3. 节点0进行快照（**块高高于110**）
../../bin/snapshot_tool -m snapshot -e 110

 4.对节点0，恢复快照
../../bin/snapshot_tool -m restore

5.实测结果：
（1）**查询不到块高64数据**
`rpc getTransactionReceipt --hash 0x1270429754fe3fb2dbb65538da9e9de2b0f83fe3ba7316b4dee6844919a360fc`
![image](https://user-images.githubusercontent.com/48231505/56876075-7e0dd900-6a77-11e9-8ce7-aab56f8e95cb.png)

（2）快照恢复共识期望从111块开始，实测是从110块开始
![image](https://user-images.githubusercontent.com/48231505/56876068-72baad80-6a77-11e9-99e2-4e5a4885e242.png)

**Expected behavior**: [见步骤5]

**Actual behavior**: [见步骤5]

**Reproduce how often**: [every]

## Versions

[develop]

**Comment by ouwenkg** [comment]
@keroro520  我在单一节点和不同节点上做了这样的测试, 都出现了类似的问题, 可以抽空看一下吗?

**Comment by keroro520** [comment]
"Snapshot" only backups `state` and `blocks` history, but not including `receipts`. So after restoring snapshot on node, historical receipts have been lost.

**Comment by kaikai1024** [comment]
> "Snapshot" only `backups` state and `blocks` history, but not including `receipts`.

@ouwenkg Please update the this description into the CITAHub Docs.

**Comment by kaikai1024** [comment]
> （2）快照恢复共识期望从111块开始，实测是从110块开始

What about this?

**Comment by ouwenkg** [comment]
Thanks a lot.  I figured out some things I ignored before.

**Comment by ouwenkg** [comment]
> > （2）快照恢复共识期望从111块开始，实测是从110块开始
> 
> What about this?

https://github.com/cryptape/cita/blob/develop/cita-chain/src/forward.rs#L678

After snapshot end, it will broadcast current status, it's normal

**Comment by janx** [comment]
Can we add an snapshot option so users can choose whether to include receipts in snapshot by themselves?

**Comment by ouwenkg** [comment]
If the snapshot has such abilitys,  there is no difference between snapshot and copy data directly.

I understand that snapshot like a lightweight data migrate tool since the constant increased data volume.

**Comment by kaikai1024** [comment]
> If the snapshot has such abilitys, there is no difference between snapshot and copy data directly.

Just 100 history blocks. that's difference, not the `receipts` part.

> Can we add an snapshot option so users can choose whether to include receipts in snapshot by themselves?

Maybe. It can be discussed.

**Comment by janx** [comment]
> If the snapshot has such abilitys, there is no difference between snapshot and copy data directly.
> 
> I understand that snapshot like a lightweight data migrate tool since the constant increased data volume.

I don't see why it's no different from data copying, the snapshot doesn't include state histories.
