### ISSUE TITLE
Version shows error in v0.23.0

### ISSUE THREAD

**Issue by leeyr338** [cryptape/cita#538]
## Description
Version shows error in v0.23.0

## Steps to Reproduce

1. [First Step]
Download [CITA release v0.23.0](https://github.com/cryptape/cita/releases/tag/v0.23.0)

2. [Second Step]
Run
```shell
$ bin/cita-env bin/cita-jsonrpc --version
```

**Expected behavior**: [What you expect to happen]
Show version as
```
JsonRpc v0.23.0-161-g12420de-dev
```

or something shows me that this is a 0.23.0 version.

**Actual behavior**: [What actually happens]
Show version as
```
JsonRpc v0.22.0-161-g12420de-dev
```

**Reproduce how often**: [What percentage of the time does it reproduce?]
100%

## Versions
v0.23.0

## Additional Information
NA.

**Comment by kaikai1024** [comment]
Reason:

It's packaged before `v0.23.0` is tagged.

**Comment by kaikai1024** [comment]
Still show `v0.23.0` when tag the `v0.23.1`.

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita/releases/tag/v0.23.1

**Comment by ouwenkg** [comment]
:+1:

**Comment by rainchen** [comment]
IMO, should not use `git tag` to set the version number, should use a const string to set version number in the source code,  for example:  https://github.com/rust-lang/rust/commit/fc50f328b0353b285421b8ff5d4100966387a997#diff-cc2473a853abfbd75a2f2d0d79eb3592R17
