### ISSUE TITLE
Start four nodes failed. ##【v0.22.0】在发布件目录下初始化一条链，然后cp3个发布件目录，分别在每个发布件目录下启动一个节点，只有0号节点启动成功，其它3个节点启动失败。

### ISSUE THREAD

**Issue by wangfh666** [cryptape/cita#540]
摘要：【CITA1-v0.22】在发布件目录下初始化一条链，然后cp3个发布件目录，分别在每个发布件目录下启动一个节点，只有0号节点启动成功，其它3个节点启动失败。

前提条件：
1、下载二进制包（v0.22）；
2、解压二进制包；

操作步骤：
1、进入发布件目录，初始化一条链；
2、cp 3个发布件目录，总共4个发布件目录；
3、分别进入每个发布件目录，启动一个节点 --KO；

预期结果：4个节点都可以启动成功。

实际结果：只有一个节点启动成功，其它3个均失败。

**Comment by kaikai1024** [comment]
error:
![Screenshot from 2019-05-05 18-39-48](https://user-images.githubusercontent.com/8768261/57192632-43b7a680-6f65-11e9-8a47-1687247da99e.png)

**Comment by leeyr338** [comment]
Please check the cita-op-helper and attach the file.
Thanks!

**Comment by wangfh666** [comment]
[cita_info.tar.gz](https://github.com/cryptape/cita/files/3147665/cita_info.tar.gz)
cuowu错误日志

**Comment by leeyr338** [comment]
从日志看，是 RabbitMq 在节点中没有正常启动导致的。

**根因分析**
1. 将发布件 copy 到同一主机的多个不同目录分别启动 CITA ；
2. 当启动第一个 CITA 节点时，RabbitMq 启动; 此时, RabbitMq 的端口会映射到主机 ；
> 默认的 rabbitmq 端口：4369(epmd)/25672(Erlang distribution)/5671，5672(AMQP)/15672(management plugin)
3. 启动第二个 CITA 节点时，RabbitMq 的端口与第一个 CITA 节点冲突，所以启动不成功；
4. 由于 RabbitMq 启动不成功，从而导致上图所示的错误产生。

**解决方案**
如果需要在一台主机上模块多台机器的 CITA 节点，请使用 docker-compose 网络隔离的方式运行 CITA 。
参考 [这里](https://docs.citahub.com/zh-CN/cita/getting-started#%E4%BD%BF%E7%94%A8docker-compose)

**Comment by kaikai1024** [comment]
补充一下：因为镜像网络是 host ，所以端口会使用主机的端口。如果对 docker 比较熟悉的话也可以用 bridge 模型进行网络隔离。
