### ISSUE TITLE
Refactor the `cita` script.

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#564]
## Description

It's hard to read.

Step by step.

**Comment by ouwenkg** [comment]
We can have a talk about this at some time, i want to finish it.

**Comment by kaikai1024** [comment]
We'll talk it on next version. It's a version about REFACTOR

**Comment by ouwenkg** [comment]
deal.

**Comment by kaikai1024** [comment]
Using Python to rewrite it.
