### ISSUE TITLE
Analysis of Performance Degradation

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#578]
## Description

date: 5/16
commit: 2887c9b60b1d5acedb23081d12ba8c86e9e8d753

**Comment by leeyr338** [comment]
`[Feature] Let native token be configurable` leads Performance degradation?

**Comment by kaikai1024** [comment]
NO SURE. 
maybe new p2p lib, check the PR of 5/16

**Comment by kaikai1024** [comment]
#588
