### ISSUE TITLE
Add symbol table to CITA release binary

### ISSUE THREAD

**Issue by leeyr338** [cryptape/cita#590]
Add symbol table to CITA release binary.

So that when CITA goes into panic, it can show which line of the code cause the `panic`. 

**Describe the solution you'd like**
This PR may increase the size of CITA binary many times, and it is better to exclude the library code.

**Comment by kaikai1024** [comment]
#353 Same issue?

**Comment by leeyr338** [comment]
Yes.

**Comment by kaikai1024** [comment]
Keep that one.
