### ISSUE TITLE
Add help usage of `create_key_addr`

### ISSUE THREAD

**Issue by kaikai1024** [cryptape/cita#617]
## Description

```
bin/create_key_addr --help/help/-h
```

**Comment by hsqlu** [comment]
Is there any docs about how to build cita on local machine?

**Comment by kaikai1024** [comment]
> Is there any docs about how to build cita on local machine?

[Build cita from source codes](https://docs.citahub.com/zh-CN/cita/hacking/compile-cita) or [Run cita from released packages](https://docs.citahub.com/zh-CN/cita/getting-started/run-cita)?

**Comment by jerry-yu** [comment]
done
