### ISSUE TITLE
rpc getTransactionCount 指定块高height 返回结果为该地址从块高为0开始到当前指定块高的交易数之和，期望显示当前块高的交易数

### ISSUE THREAD

**Issue by QingYanL** [cryptape/cita#652]
## Description

[rpc getTransactionCount 指定块高height 返回结果为该地址总的交易数之和，期望显示当前块高的交易数]

## Steps to Reproduce

1. 多次，间隔一定时间，保证在交易在不同块内[`transfer --address 0x0d5c23dc41956c8aca3b6f3fa581a4fd640f7997 --private-key 0x5f0258a4778057a8a7d97809bd209055b2fbafa654ce7d31ec7191066b9225e6 --value 10` ]

2. [获取其中一个交易的回执信息，查看该交易所在的块高 `rpc getTransactionReceipt --hash`]

3. [查看交易在指定块高的交易数目 rpc getTransactionCount --address 0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523 --height 0x36]    **返回值显示的是该地址所有交易数目之和。**

4.[通过块高，查询当前块内的交易数目：` rpc getBlockByNumber --height 0x36`] 返回结果：和步骤3数据不一致
![image](https://user-images.githubusercontent.com/48231505/59667775-dd6fa600-91e9-11e9-96f4-4a64d0a3543a.png)

**Expected behavior**: [rpc getTransactionCount 指定块高返回结果为指定块高的交易数之和，见文档说明 https://docs.citahub.com/zh-CN/cita/rpc-guide/rpc#gettransactioncount ]

**Actual behavior**: [rpc getTransactionCount 指定块高height 返回结果为该地址从块高为0开始到当前指定块高的交易数之和]

**Reproduce how often**: [every]

## Versions

[v0.24  or v0.24.1]

**Comment by ouwenkg** [comment]
I will deep into this issue, Thanks!

**Comment by ouwenkg** [comment]
This bug has been around for a long time, when revoking `geTransactionCount`,  the returned result is  current nonce of the address. This value represent all transactions counts sended from the address from block 0 to latest.

Code like this:
```
 Request::transaction_count(tx_count) => {
                trace!("transaction count request from jsonrpc {:?}", tx_count);
                let _ = serde_json::from_str::<CountOrCode>(&tx_count)
                    .map_err(|err| {
                        response.set_code(ErrorCode::query_error());
                        response.set_error_msg(format!("{:?}", err));
                    })
                    .map(|tx_count| {
                        let address = Address::from_slice(tx_count.address.as_ref());
                        match command::nonce_at(
                            &self.command_req_sender,
                            &self.command_resp_receiver,
                            address,
                            tx_count.block_id.into(),
                        ) {
                            Some(nonce) => {
                                response.set_transaction_count(u64::from(nonce));
                            }
                            None => {
                                response.set_transaction_count(0);
                            }
                        };
                    });
            }
```

**Comment by kaikai1024** [comment]
> 指定块高返回结果为指定块高的交易数之和

具体是哪里说明了这个意思呢？

**Comment by ouwenkg** [comment]
> > 指定块高返回结果为指定块高的交易数之和
> 
> 具体是哪里说明了这个意思呢？

https://docs.citahub.com/zh-CN/next/cita/rpc-guide/rpc#gettransactioncount

**Comment by kaikai1024** [comment]
https://docs.citahub.com/zh-CN/cita/rpc-guide/rpc#gettransactioncount

Check the eglish version.

**Comment by kaikai1024** [comment]
>  integer of the number of transactions sent from this address, based on the given BlockNumber.

How does this translate to "指定账户在指定块中交易数量"?

https://web3js.readthedocs.io/en/1.0/web3-eth.html#getblocktransactioncount

https://web3js.readthedocs.io/en/1.0/web3-eth.html#gettransactioncount

**Comment by ouwenkg** [comment]
> > integer of the number of transactions sent from this address, based on the given BlockNumber.
> 
> How does this translate to "指定账户在指定块中交易数量"?
> 
> https://web3js.readthedocs.io/en/1.0/web3-eth.html#getblocktransactioncount
> 
> https://web3js.readthedocs.io/en/1.0/web3-eth.html#gettransactioncount

应该是查询基于某一个块高的交易总数. 我明确一下文档吧.
