### ISSUE TITLE
Something wrong when append node. ## 摘要：【CITA】新增普通节点出错

### ISSUE THREAD

**Issue by wangfh666** [cryptape/cita#671]
摘要：【CITA】新增普通节点出错
![截图](https://user-images.githubusercontent.com/41322861/60325382-bec39900-99b9-11e9-8f28-dc95691f8830.jpg)

前提条

操作步骤：
1、bin/cita create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4007,127.0.0.1:4008" --enable_version 初始化一条链，生成共识节点0，1，7，8；
2、bin/cita append --chain_name test-chain --node "127.0.0.1:400[2-6]" 新增普通节点2，3，4，5，6；
3、vi test-chain/[0-8]/network.toml 添加配置项 enable_discovery = false ，并且节点0中不保存IP，节点1中仅保存节点0的IP，节点2中仅保存节点1的IP，节点3中仅保存节点2的IP，依次类推；
4、setup 和 start 所有节点；
5、bin/cita append --chain_name test-chain --node "127.0.0.1:4009"  新增节点9 --KO

预期结果：可以正常创建普通节点。
实际结果：创建普通节点报错。

**Comment by leeyr338** [comment]
需要 apend  完后，再更改。

**Comment by leeyr338** [comment]
当前 append 命令会在每个原有的节点配置中添加内容。

[[peers]] 下可以没有内容，但不能把 [[peers]] 这个标签删除。

**Comment by kaikai1024** [comment]
> [[peers]] 下可以没有内容，但不能把 [[peers]] 这个标签删除。

yes. it's the reason. 
i am thinking if we can check this situation and add this label?

**Comment by leeyr338** [comment]
> > [[peers]] 下可以没有内容，但不能把 [[peers]] 这个标签删除。
> 
> yes. it's the reason.
> i am thinking if we can check this situation and add this label?

I think this is a very rare scene that we can do it later.

**Comment by kaikai1024** [comment]
> I think this is a very rare scene that we can do it later.

agree

**Comment by kaikai1024** [comment]
Limit: should not remove the `[[peers]]` label of network config.
