### ISSUE TITLE
Better description

### ISSUE THREAD

**Issue by blankwu** [cryptape/cita#693]
## Description

Better description，change 'ok' to 'success'

## Additional Information

https://github.com/cryptape/cita/blob/f765d6514aa47f7a9d264f8cbc7491a411a385c8/scripts/cita.sh#L185

https://github.com/cryptape/cita/blob/f765d6514aa47f7a9d264f8cbc7491a411a385c8/scripts/cita.sh#L205

**Comment by jerry-yu** [comment]
trivial command's notice modify
