### ISSUE TITLE
create chain error with --init_token and  VersionManager.version=2 

### ISSUE THREAD

**Issue by QingYanL** [cryptape/cita#696]
## Description

[create chain error with --init_token and  VersionManager.version=2 ]

## Steps to Reproduce

1. **[create chain]**
` bin/cita create --chain_name lytest-chain --jsonrpc_port 3337 --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523"  --init_token "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"  --contract_arguments SysConfig.economicalModel=1  --contract_arguments VersionManager.version=2  --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003" `

![image](https://user-images.githubusercontent.com/48231505/61508292-cb1c9e00-aa1b-11e9-9b1e-095944733992.png)

2. **[error: ]**  
`thread 'main' panicked at 'assertion failed: 4 * 8 >= slice.len()', /opt/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-types-0.3.2/src/uint.rs:32:1
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`

![image](https://user-images.githubusercontent.com/48231505/61508310-dbcd1400-aa1b-11e9-80f6-3c41807242d5.png)

3. **[create chain success]**  
`bin/cita create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003" --enable_version --contract_arguments SysConfig.economicalModel=1 --init_token 0xffffffffffffffffffffffffffffff`

**Expected behavior**: [create chain success with step 1]

**Actual behavior**: [create chain error ]

**Reproduce how often**: [every]

## Versions

[v0.25]

**Comment by ouwenkg** [comment]
Please check your init token param. It's too for for U256.

```sh
bin/cita bebop create --chain_name lytest-chain --jsonrpc_port 3337 --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --init_token "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" --contract_arguments SysConfig.economicalModel=1 --contract_arguments VersionManager.version=2 --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"
```

**Comment by QingYanL** [comment]
I check init_token to long ,it not a bug @ouwenkg
