### ISSUE TITLE
账户余额扣去转账消耗的quato后，余额大于转账金额转账失败

### ISSUE THREAD

**Issue by QingYanL** [cryptape/cita#698]
## Description

[账户余额扣去转账消耗的quato后，余额大于转账金额转账失败]

## Steps to Reproduce

1. 转账失败：
**创建账户A，账户B；
admin 给账户A 转账30000 * 10^6 ；
账户A 给账户B  转账 1000，消耗"cumulativeQuotaUsed": "0x5208" 值为：  21000 * 10^6，
失败"errorMessage": "Cost of transaction exceeds sender balance."；
转账后，账户A 余额 9000 * 10^6 ；**

![image](https://user-images.githubusercontent.com/48231505/61518413-04650600-aa3c-11e9-8e79-bc7089e94f50.png)
![image](https://user-images.githubusercontent.com/48231505/61518531-56a62700-aa3c-11e9-85ac-017335ad0202.png)
![image](https://user-images.githubusercontent.com/48231505/61518797-04193a80-aa3d-11e9-8993-c185df459a3c.png)

2. 转账成功：
**创建账户A，账户B；
admin给账户A转账 30001 * 10^6；
账户A 给账户B 转账 1000，消耗"cumulativeQuotaUsed": "0x5208" 值为：  21000 * 10^6；
账户A 余额：0x218805858 值为9000999000；
经计算： 账户A 转账后余额 + 账户A转账给账户B 消耗的quota + 账户A 转账给账户B的金额 = 账户A 转账前余额
9000999000 + 21000000000 + 1000 = 30001000000**

**Expected behavior**: [步骤一中账户A余额大于1000 期望转账成功]

**Actual behavior**: [步骤一转账扣去quota后余额仍大于转账金额，转账失败]

**Reproduce how often**: [every]

## Versions

[v0.25]

**Comment by leeyr338** [comment]
请问，交易的 t.gas 设的是多少？

**Comment by leeyr338** [comment]
对于转帐来说，也会先做交易前的检查。也即：
balance > (t.gas + t.value) * quota_price
在这个场景里，我怀疑交易的 t.gas 设得比较大，请确认一下。
