### ISSUE TITLE
CITA v0.25.0 version info is incorrect

### ISSUE THREAD

**Issue by rainchen** [cryptape/cita#747]
## Description

CITA v0.25.0 version info is incorrect
Found by CITA-Monitor:

<img width="251" alt="Screen Shot 2019-07-31 at 11 15 04 AM" src="https://user-images.githubusercontent.com/71397/62181082-a82bab80-b384-11e9-94a9-514a702b603b.png">

using CITA version  v0.25.0 88b90bb

![Screen Shot 2019-07-31 at 11 11 15 AM](https://user-images.githubusercontent.com/71397/62181130-c72a3d80-b384-11e9-825b-64f2e0e78a8a.png)

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on …]

**Expected behavior**: should be `v0.25.0 88b90bb`

**Actual behavior**:  check the screen shot

**Reproduce how often**: always

## Versions

CITA v0.25.0

**Comment by kaikai1024** [comment]
Yeah. i've tried the released package, it does show the wrong version info.
And when i build the tag `v0.25.0` on my own pc, it shows right vrsion. 

Maybe the package's problem.

I'll check it.

**Comment by kaikai1024** [comment]
Check the patch version:

https://github.com/cryptape/cita/releases/tag/v0.25.1
