### ISSUE TITLE
develop 分支 CI 挂掉的原因

### ISSUE THREAD

**Issue by nanmuxiusi** [cryptape/cita#773]
error: Vulnerable crates found!

ID:     RUSTSEC-2019-0011
Crate:     memoffset
Version: 0.2.1
Date:     2019-07-16
URL:     https://github.com/Gilnaa/memoffset/issues/9#issuecomment-505461490
Title:     Flaw in offset_of and span_of causes SIGILL, drops uninitialized memory of arbitrary type on panic in client code
Solution: upgrade to: >= 0.5.0

error: 1 vulnerability found!
Makefile:41: recipe for target 'security_audit' failed
make: *** [security_audit] Error 1

**Comment by kaikai1024** [comment]
Upgrade `crossbeam` and `crossbeam-channel`

**Comment by kaikai1024** [comment]
https://github.com/cryptape/cita/pulls?q=is%3Apr+is%3Aclosed+label%3A"reopen+later"
