### ISSUE TITLE
如何接入测试网

### ISSUE THREAD

**Issue by hunjixin** [cryptape/cita#775]
文档有的链接坏的，有的不够详细。
请问我该如何接入测试网络，需要进行什么配置，配置文件到哪里获取。

**Comment by nanmuxiusi** [comment]
测试链：https://docs.citahub.com/zh-CN/next/toolchain/testnet/testchain
配置说明：https://docs.citahub.com/zh-CN/next/cita/configuration-guide/chain-config
如果需要快速启链可参考快速入门：https://docs.citahub.com/zh-CN/next/cita/getting-started/setup
请问有哪些链接坏了，我们修复下；另外，觉得哪些地方不够详细，也请具体说明下，谢谢！

**Comment by hunjixin** [comment]
您第一个给的链接页面里面 https://node.cryptape.com/ 不可用
现在需要几条命令帮助我快速直接的接入测试网络，

部署指南里面几个跳转基本都是404

**Comment by kaikai1024** [comment]
新增节点连测试网的方式是本地有 genesis （和测试网一致的情况下），由于支持 p2p ，所以只需要知道一个节点的地址就可以了。
不过我们暂时没提供 genesis 下载方式，可以自由使用测试网，现在暂时不支持连入新节点

**Comment by leeyr338** [comment]
@hunjixin , 我理解你接入测试网的需求是使用测试网部署合约、发送交易等一系列动作，而不是要自己部署一个节点，对吗？
如果是这样，那么 https://node.cryptape.com 是这样使用的 （我假设你安装了 cita-cli，并且熟悉 cita-cli 的一些基本操作 ）：
```shell
$ cita-cli rpc blockNumber --url https://node.cryptape.com
  "id": 1,
  "jsonrpc": "2.0",
  "result": "0x79c954"
}
```
如果你想向测试链部署合约、或发送交易，直接使用这个 url 便可。

**Comment by hunjixin** [comment]
@leeyr338  不是哦，我是要调试下这代码流程，已经编译好了，但是我又不想自己搭建bft出块。所以希望可以简单的接入。 一般现在很多区块链项目会提供solo共识的策略，也建议这边弄一个，毕竟bft比较麻烦的。

**Comment by leeyr338** [comment]
另外，关于测试链的文档确实不完善，我建了个 issue:
https://github.com/cryptape/citahub-docs/issues/345

**Comment by leeyr338** [comment]
> @leeyr338 不是哦，我是要调试下这代码流程，已经编译好了，但是我又不想自己搭建bft出块。所以希望可以简单的接入。 一般现在很多区块链项目会提供solo共识的策略，也建议这边弄一个，毕竟bft比较麻烦的。

谢谢建议，你的意思是更改了 cita 的代码，然后想连入测试网，使用测试网上的数据进行测试吗？

**Comment by hunjixin** [comment]
@leeyr338  嗯嗯，就是想看下你们这边的处理的流程。

**Comment by rainchen** [comment]
> @leeyr338 不是哦，我是要调试下这代码流程，已经编译好了，但是我又不想自己搭建bft出块。所以希望可以简单的接入。 一般现在很多区块链项目会提供solo共识的策略，也建议这边弄一个，毕竟bft比较麻烦的。

起单节点很简单，我们其他toolchain 里有做了一些封装：

https://github.com/cryptape/cita-monitor/tree/develop/test#to-start-1-node

```
To start 1 node：
generate node config: $ make config-node
start 1 node: $ make start-node
```

@leeyr338 @kaikai1024 我们是要做下cita-node 的 Docker Image，让开发者使用更简单些

**Comment by leeyr338** [comment]
> > @leeyr338 不是哦，我是要调试下这代码流程，已经编译好了，但是我又不想自己搭建bft出块。所以希望可以简单的接入。 一般现在很多区块链项目会提供solo共识的策略，也建议这边弄一个，毕竟bft比较麻烦的。
> 
> 起单节点很简单，我们其他toolchain 里有做了一些封装：
> 
> https://github.com/cryptape/cita-monitor/tree/develop/test#to-start-1-node
> 
> ```
> To start 1 node：
> generate node config: $ make config-node
> start 1 node: $ make start-node
> ```
> 
> @leeyr338 @kaikai1024 我们是要做下cita-node 的 Docker Image，让开发者使用更简单些

从 @hunjixin 的需求看，他是想调度 CITA 的代码，使用制做好的 Docker Image 不合适。而且也并不比现在的方式简单多少，但却失去了灵活性。

**Comment by kaikai1024** [comment]
solo 共识的需求我们自己这边其实也有，我个人平时调试一般也都是单起一个节点。 bft 共识也是支持单节点的（配置的时候设置一个节点）。

针对开发者调试这方面的支持以及文档确实有点缺失，可以多点考虑在这些方面

**Comment by leeyr338** [comment]
> @leeyr338 嗯嗯，就是想看下你们这边的处理的流程。

如果是这样的话，你可以使用：
https://docs.citahub.com/zh-CN/cita/getting-started/run-cita
中描述的步骤，在你的 target/intasll 使用 Docker 生成与启动一条 4 个节点的链，成本也非常低。
```shell
bin/cita create --super_admin "0x37d1c7449bfe76fe9c445e626da06265e9377601" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"
```
另外，现在 CITA 的测试链是为了方便 DApp 开发者使用，所以我们需要保证它的稳定运行。因此对节点的接入是有控制的。

**Comment by hunjixin** [comment]
> solo 共识的需求我们自己这边其实也有，我个人平时调试一般也都是单起一个节点。 bft 共识也是支持单节点的（配置的时候设置一个节点）。
> 
> 针对开发者调试这方面的支持以及文档确实有点缺失，可以多点考虑在这些方面

bft单节点这个现在不需要改什么东西就可以用么，如果不行我在部署4个bft吧

**Comment by kaikai1024** [comment]
> bft单节点这个现在不需要改什么东西就可以用么，如果不行我在部署4个bft吧

不用的，`--nodes` 一个节点就行了，例如：

```
bin/cita create --super_admin "0x37d1c7449bfe76fe9c445e626da06265e9377601" --nodes "127.0.0.1:4000"
```

然后 setup/start 一个节点 0 就行

**Comment by hunjixin** [comment]
@kaikai1024 你们有技术群的么

**Comment by kaikai1024** [comment]
@hunjixin 这个 @nanmuxiusi 可能更清楚一点。
除了 issue 外，公开的有 https://talk.citahub.com/  论坛，citahub 网站 https://www.citahub.com/#introductionArea

**Comment by hunjixin** [comment]
搞定了，每个组件都弄个terminal起的，forever那个不要了

**Comment by nanmuxiusi** [comment]
> @kaikai1024 你们有技术群的么

你可以加下方微信，会将你拉至相应的群里，但目前技术相关的问题主要是在 CITAHub 论坛（ https://talk.citahub.com/ ）上讨论～欢迎你的加入！

<img width="299" alt="image" src="https://user-images.githubusercontent.com/42529063/62991727-5eae8680-be83-11e9-9c17-5f3277c9e143.png">

**Comment by nanmuxiusi** [comment]
> 您第一个给的链接页面里面 https://node.cryptape.com/ 不可用
> 现在需要几条命令帮助我快速直接的接入测试网络，
> 
> 部署指南里面几个跳转基本都是404

感谢你的反馈，我们尽快修复！
