### ISSUE TITLE
优化合约生成

### ISSUE THREAD

**Issue by nanmuxiusi** [cryptape/cita#779]
1. 生成合约时，nonce, validUntilBlock, version, chainId这几个参数都是重复要输入的，自动获取或者通过构造函数传入
 2. 非payable的函数生成方法应该不用传value
 3. 生成合约类时候对于 payable 函数多一个 weivalue，大家不理解，最好能在文档或社区中增加一篇详细说明
来源用户反馈：https://talk.citahub.com/t/topic/777

**Comment by kaikai1024** [comment]
It's better to transfer it to the cita-sdk-java repo.  @nanmuxiusi

**Comment by nanmuxiusi** [comment]
> It's better to transfer it to the cita-sdk-java repo. @nanmuxiusi

OK

**Comment by kaikai1024** [comment]
You can transfer it, no need to close and new another one.

check this:

![Screenshot from 2019-08-07 09-47-03](https://user-images.githubusercontent.com/8768261/62588459-55a83d00-b8f8-11e9-989f-df3174e1f46b.png)
