### ISSUE TITLE
delete cita-bft and cita-forever module

### ISSUE THREAD

**Issue by LiQingMuBai** [cryptape/cita#863]
## Description

[Description of the issue]

## Steps to Reproduce

1. [First Step]
cargo test failed
2. [Second Step]
3. [and so on …]

**Expected behavior**: [What you expect to happen]

**Actual behavior**: [What actually happens]

**Reproduce how often**: [What percentage of the time does it reproduce?]

## Versions

[The versions of the CITA, operating systems or VM software you use]

## Additional Information

[Any other information which would be helpful to reproduce the issue].

**Comment by ouwenkg** [comment]
？
