### ISSUE TITLE
can't deploy contract with cita1.0  by cita_cil

### ISSUE THREAD

**Issue by PanYu-Next** [cryptape/cita#866]
## Description

在CITA 1.0 版本上，根据安装官方文档，cita_cli方式部署合约失败，Exector微服务产生panice，无法重启拉起该服务，具体Error log信息请参考下面；
但在CITA 0.24 版本却不会出现该问题，操作方法一样；

## Steps to Reproduce
1. 启动cita 网络，正常

2. 部署合约
**执行动作**： cita-cli rpc sendRawTransaction --private-key  0xabfb72cb9f296f4759566035ceaba7527bf693a8dd946483bfd0e11f4293dd0b --code  
0x608060405234801561001057600080fd5b5060405161087f38038061087f833981018060405281019080805182019291905050508060009080519060200190610049929190610050565b50506100f5565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061009157805160ff19168380011785556100bf565b828001600101855582156100bf579182015b828111156100be5782518255916020019190600101906100a3565b5b5090506100cc91906100d0565b5090565b6100f291905b808211156100ee5760008160009055506001016100d6565b5090565b90565b61077b806101046000396000f300608060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063704214511461005c578063a4136862146101aa578063cfae321714610213575b600080fd5b34801561006857600080fd5b506100c3600480360381019080803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091929192905050506102a3565b604051808060200180602001838103835285818151815260200191508051906020019080838360005b838110156101075780820151818401526020810190506100ec565b50505050905090810190601f1680156101345780820380516001836020036101000a031916815260200191505b50838103825284818151815260200191508051906020019080838360005b8381101561016d578082015181840152602081019050610152565b50505050905090810190601f16801561019a5780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b3480156101b657600080fd5b50610211600480360381019080803590602001908201803590602001908080601f016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050919291929050505061034e565b005b34801561021f57600080fd5b506102286104b8565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561026857808201518184015260208101905061024d565b50505050905090810190601f1680156102955780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b606080600083818054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561033e5780601f106103135761010080835404028352916020019161033e565b820191906000526020600020905b81548152906001019060200180831161032157829003601f168201915b5050505050915091509150915091565b61038d816040805190810160405280600a81526020017f48656c6c6f204d6172790000000000000000000000000000000000000000000081525061055a565b151515610402576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252601b8152602001807f6772656574696e67e4b88de883bde4bdbf48656c6c6f204d617279000000000081525060200191505060405180910390fd5b80600090805190602001906104189291906106aa565b507fc8aaea408f296d4e77881060cba7a49144f545e06bce5953df6a2a252df836fe816040518080602001828103825283818151815260200191508051906020019080838360005b8381101561047b578082015181840152602081019050610460565b50505050905090810190601f1680156104a85780820380516001836020036101000a031916815260200191505b509250505060405180910390a150565b606060008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156105505780601f1061052557610100808354040283529160200191610550565b820191906000526020600020905b81548152906001019060200180831161053357829003601f168201915b5050505050905090565b600060608060008592508491508151835114151561057b57600093506106a1565b600090505b825181101561069c57818181518110151561059757fe5b9060200101517f010000000000000000000000000000000000000000000000000000000000000090047f0100000000000000000000000000000000000000000000000000000000000000027effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916838281518110151561061257fe5b9060200101517f010000000000000000000000000000000000000000000000000000000000000090047f0100000000000000000000000000000000000000000000000000000000000000027effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff191614151561068f57600093506106a1565b8080600101915050610580565b600193505b50505092915050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106106eb57805160ff1916838001178555610719565b82800160010185558215610719579182015b828111156107185782518255916020019190600101906106fd565b5b509050610726919061072a565b5090565b61074c91905b80821115610748576000816000905550600101610730565b5090565b905600a165627a7a72305820dbdc8a7b83cf738157d89fb4a5d3344318984513fb8605101d3610510bede9be0029

output:
{
  "id": 4,
  "jsonrpc": "2.0",
  "result": {
    "hash": "0x1c3c5b97af842a30fce91c6346d1b448105ca6ccee5ae0a54bed9a6051674d01",
    "status": "OK"
  }
}

**异常行为**：Exector微服务产生的panic，Error log信息如下；
**重复频率**：一直

## Versions
* cita 版本：v1.0.0
* solc版本：v0.4.24
* Docker 版本：v18.09.2
* cita_image版本：ubuntu-18.04-20190829
* mac os: 10.14

## Additional Information
Exector微服务产生的 Error log:
* 2019-10-14 - 08:44:13 | panic_hook           - 59    | ERROR -
============================
stack backtrace:
   0:     0x55c196645efd - backtrace::backtrace::trace::h427274634b26cc90
   1:     0x55c196645ae2 - backtrace::capture::Backtrace::new::h24b4be509c889493
   2:     0x55c196644df4 - panic_hook::panic_hook::h49ebbf6f4135f29c
   3:     0x55c196644b28 - core::ops::function::Fn::call::h4af4df279732d685
   4:     0x55c196b4ca78 - rust_panic_with_hook
                        at src/libstd/panicking.rs:482
   5:     0x55c1966ae954 - std::panicking::begin_panic::h25f19b0c271b79cc
   6:     0x55c1966a554a - cita_vm::evm::interpreter::Interpreter::run::h0e671fbb0862e93a
   7:     0x55c1965305f2 - cita_vm::executive::call::h27a38972fbbaaa74
   8:     0x55c196534d00 - cita_vm::executive::create::hb6304413b602930d
   9:     0x55c19653229e - cita_vm::executive::exec::h359da34280152509
  10:     0x55c19652c52f - <core_executor::cita_executive::CitaExecutive<'a, B>>::call_evm::h48edab47b81c678e
  11:     0x55c196528930 - <core_executor::cita_executive::CitaExecutive<'a, B>>::exec::hb83e577da3c09218
  12:     0x55c1965399ee - core_executor::libexecutor::block::ExecutedBlock::apply_transaction::h20433847d299ccf3
  13:     0x55c196509d75 - <core_executor::libexecutor::executor::Executor as core_executor::libexecutor::fsm::FSM>::fsm_execute::hb68ec822f00e6d96
  14:     0x55c196509295 - <core_executor::libexecutor::executor::Executor as core_executor::libexecutor::fsm::FSM>::into_fsm::hcdcd84005f540b30
  15:     0x55c196505b44 - core_executor::libexecutor::executor::Executor::do_loop::h0c5248e4483cbcc0
  16:     0x55c196400f64 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5061ac345d18370c
  17:     0x55c1963f1403 - std::panicking::try::do_call::hd9779eaacd8b33a0
  18:     0x55c196b51d89 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:87
  19:     0x55c1964030b7 - <F as alloc::boxed::FnBox<A>>::call_box::h40c996b93aa16e12
  20:     0x55c196b510fd - call_once<(),()>
                        at /rustc/6c2484dc3c532c052f159264e970278d8b77cdc9/src/liballoc/boxed.rs:759
                         - start_thread
                        at src/libstd/sys_common/thread.rs:14
                         - thread_start
                        at src/libstd/sys/unix/thread.rs:81
  21:     0x7f3288f186da - start_thread
  22:     0x7f3288a2988e - __clone
  23:                0x0 - <unknown>

position:
Thread <unnamed> panicked at invalid memory: store empty, /opt/.cargo/git/checkouts/cita-vm-3a932e6e40f5bfc6/535c36d/src/evm/memory.rs:11

This is a bug. Please report it at:

    https://github.com/cryptape/cita/issues/new?labels=bug&template=bug_report.md

============================

**Comment by jerry-yu** [comment]
谢谢，抓紧重现、修复中

**Comment by jerry-yu** [comment]
原因是evm的mem的copy操作的offset 超过了mem的原来大小，导致了panic。

会最近发布的1.0.1中修复

**Comment by jerry-yu** [comment]
https://github.com/cryptape/cita/releases/tag/v1.0.1
在1.0.1版本修复
