### ISSUE TITLE
软件升级后，不出块

### ISSUE THREAD

**Issue by 15667076526** [cryptape/cita#944]
## Description

[Description of the issue]

单节点，发布件升级
版本从JsonRpc 20.2.0-d8f65876升级到JsonRpc v0.24.0-dev
升级后启动节点，发现不出块
使用top查看状态，发现executor服务没有了
查看executor日志，发现了ERROR，提示我是个Bug，进行提交
![1616138040(1)](https://user-images.githubusercontent.com/34765662/111744471-40fa9c00-88c6-11eb-8def-c9bbea75cb73.jpg)

**Comment by jerry-yu** [comment]
grpc_port 的配置项没了
